[package]
name = "tauri-plugin-mish-vpn"
version.workspace = true
edition.workspace = true
license.workspace = true
links = "tauri-plugin-mish-vpn"
build = "build.rs"

[lib]
name = "tauri_plugin_mish_vpn"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
tauri = { version = "2.11.5", features = [] }
thiserror = "2.0.17"

[build-dependencies]
tauri-plugin = { version = "2.5.4", features = ["build"] }
