// Generated by scripts/generate-android-platform-facts.ts; do not edit.
package com.asuka109.mish.vpn

import org.json.JSONObject

internal const val ANDROID_PLATFORM_FACTS_VERSION = 1
internal const val ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX = 9007199254740991L
internal const val ANDROID_PLATFORM_FACTS_GOLDEN_JSON = "{\"activationFailure\":null,\"activationSessionId\":null,\"activeNetwork\":false,\"configFailureInjectionAvailable\":false,\"coreAbiVersion\":1,\"coreAvailability\":\"available\",\"coreCommit\":\"e26714a181ac0e2fa803453c0a8e9a9ce94e31cb\",\"coreConfigState\":\"unloaded\",\"coreRunning\":false,\"coreVersion\":\"v1.19.29\",\"coreWrapperRevision\":\"mish-mobile-core-v1\",\"dnsApplied\":false,\"event\":\"observation\",\"factSequence\":7,\"factsVersion\":1,\"lifecycleAuthority\":null,\"loadedConfigDigest\":null,\"loadedConfigRevision\":null,\"notificationPermission\":\"required\",\"observedAtMillis\":1700000000000,\"platformSessionId\":\"platform-session-1\",\"protectedSocketCount\":0,\"publicRequestObserved\":false,\"recoveryEvidence\":\"none\",\"routesApplied\":false,\"serviceForeground\":false,\"tunEstablished\":false,\"validatedConfigDigest\":null,\"validatedConfigRevision\":null,\"vpnPermission\":\"required\"}"

internal enum class PlatformEventKind(val wireName: String) {
    ACTIVATION_COMPLETED("activation-completed"),
    ACTIVATION_FAILED("activation-failed"),
    ACTIVATION_PROGRESS("activation-progress"),
    CONSENT_RESULT("consent-result"),
    CORE_EXITED("core-exited"),
    NETWORK_CHANGED("network-changed"),
    NOTIFICATION_RESULT("notification-result"),
    OBSERVATION("observation"),
    REVOKED("revoked"),
    SERVICE_DESTROYED("service-destroyed"),
    STOP_COMPLETED("stop-completed"),
}

internal enum class PlatformFailureKind(val wireName: String) {
    CLEANUP_FAILED("cleanup-failed"),
    CONFIGURATION_NOT_LOADED("configuration-not-loaded"),
    CORE_EXITED("core-exited"),
    CORE_START_FAILED("core-start-failed"),
    CORE_UNAVAILABLE("core-unavailable"),
    NETWORK_UNAVAILABLE("network-unavailable"),
    PERMISSION_REVOKED("permission-revoked"),
    PUBLIC_REQUEST_FAILED("public-request-failed"),
    TUN_ESTABLISH_FAILED("tun-establish-failed"),
}

internal enum class PlatformRecoveryEvidence(val wireName: String) {
    FOREGROUND_EXPECTED("foreground-expected"),
    INVALID("invalid"),
    NONE("none"),
}

private val VPN_PERMISSIONS = setOf("granted", "required", "unknown")
private val NOTIFICATION_PERMISSIONS = setOf("denied", "granted", "not-required", "required")
private val PLATFORM_AVAILABILITY = setOf("available", "unavailable")
private val CORE_CONFIG_STATES = setOf("loaded", "unknown", "unloaded")
private val IDENTIFIER_PATTERN = Regex("^[A-Za-z0-9._-]{1,128}$")
private val DIGEST_PATTERN = Regex("^[0-9a-f]{64}$")
private val CORE_COMMIT_PATTERN = Regex("^[0-9a-f]{7,64}$")
private val CORE_VERSION_PATTERN = Regex("^[A-Za-z0-9._+-]{1,32}$")
private val CORE_WRAPPER_PATTERN = Regex("^[A-Za-z0-9._-]{1,64}$")

internal fun validatePlatformFacts(facts: MobilePlatformFacts) {
    check(facts.factsVersion == ANDROID_PLATFORM_FACTS_VERSION) { "Unsupported factsVersion" }
    check(facts.factSequence in 1..ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX) { "Invalid factSequence" }
    check(facts.observedAtMillis in 0..ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX) { "Invalid observedAtMillis" }
    check(facts.platformSessionId.matches(IDENTIFIER_PATTERN)) { "Invalid platformSessionId" }
    check(facts.activationSessionId == null || facts.activationSessionId.matches(IDENTIFIER_PATTERN)) { "Invalid activationSessionId" }
    check(facts.event in PlatformEventKind.entries.map { it.wireName }) { "Unknown platform event" }
    check(facts.activationFailure == null || facts.activationFailure in PlatformFailureKind.entries.map { it.wireName }) { "Unknown platform failure" }
    check(facts.recoveryEvidence in PlatformRecoveryEvidence.entries.map { it.wireName }) { "Unknown recovery evidence" }
    check(facts.vpnPermission in VPN_PERMISSIONS) { "Unknown VPN permission" }
    check(facts.notificationPermission in NOTIFICATION_PERMISSIONS) { "Unknown notification permission" }
    check(facts.coreAvailability in PLATFORM_AVAILABILITY) { "Unknown Core availability" }
    check(facts.coreConfigState in CORE_CONFIG_STATES) { "Unknown Core configuration state" }
    check(facts.protectedSocketCount in 0..1L) { "Invalid protectedSocketCount" }
    check(facts.coreAbiVersion == null || facts.coreAbiVersion == 1) { "Invalid Core ABI version" }
    check(facts.coreCommit == null || facts.coreCommit.matches(CORE_COMMIT_PATTERN)) { "Invalid Core commit" }
    check(facts.coreVersion == null || facts.coreVersion.matches(CORE_VERSION_PATTERN)) { "Invalid Core version" }
    check(facts.coreWrapperRevision == null || facts.coreWrapperRevision.matches(CORE_WRAPPER_PATTERN)) { "Invalid Core wrapper revision" }
    val coreIdentityComplete = facts.coreAbiVersion != null && facts.coreCommit != null && facts.coreVersion != null && facts.coreWrapperRevision != null
    check((facts.coreAvailability == "available") == coreIdentityComplete) { "Core availability and identity disagree" }
    check(facts.loadedConfigDigest == null || facts.loadedConfigDigest.matches(DIGEST_PATTERN)) { "Invalid loaded digest" }
    check(facts.validatedConfigDigest == null || facts.validatedConfigDigest.matches(DIGEST_PATTERN)) { "Invalid validated digest" }
    check(facts.loadedConfigRevision == null || facts.loadedConfigRevision.matches(IDENTIFIER_PATTERN)) { "Invalid loaded revision" }
    check(facts.validatedConfigRevision == null || facts.validatedConfigRevision.matches(IDENTIFIER_PATTERN)) { "Invalid validated revision" }
    val loadedComplete = facts.loadedConfigDigest != null && facts.loadedConfigRevision != null
    check((facts.coreConfigState == "loaded") == loadedComplete) { "Loaded configuration identity is inconsistent" }
    check((facts.validatedConfigDigest == null) == (facts.validatedConfigRevision == null)) { "Validated configuration identity is incomplete" }
    check(facts.lifecycleAuthority == null || (
        facts.lifecycleAuthority.isValid() &&
            facts.lifecycleAuthority.scopeEpoch <= ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX &&
            facts.lifecycleAuthority.admittedRevision <= ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX &&
            facts.lifecycleAuthority.effectIdentity.toLongOrNull()?.let { it in 1..ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX } == true
    )) { "Invalid lifecycle authority" }
}

internal fun platformFactsToJson(facts: MobilePlatformFacts): JSONObject {
    validatePlatformFacts(facts)
    return JSONObject()
        .put("activationFailure", facts.activationFailure ?: JSONObject.NULL)
        .put("activationSessionId", facts.activationSessionId ?: JSONObject.NULL)
        .put("activeNetwork", facts.activeNetwork)
        .put("configFailureInjectionAvailable", facts.configFailureInjectionAvailable)
        .put("coreAbiVersion", facts.coreAbiVersion ?: JSONObject.NULL)
        .put("coreAvailability", facts.coreAvailability)
        .put("coreCommit", facts.coreCommit ?: JSONObject.NULL)
        .put("coreConfigState", facts.coreConfigState)
        .put("coreRunning", facts.coreRunning)
        .put("coreVersion", facts.coreVersion ?: JSONObject.NULL)
        .put("coreWrapperRevision", facts.coreWrapperRevision ?: JSONObject.NULL)
        .put("dnsApplied", facts.dnsApplied)
        .put("event", facts.event)
        .put("factSequence", facts.factSequence)
        .put("factsVersion", facts.factsVersion)
        .put("lifecycleAuthority", facts.lifecycleAuthority?.toJson() ?: JSONObject.NULL)
        .put("loadedConfigDigest", facts.loadedConfigDigest ?: JSONObject.NULL)
        .put("loadedConfigRevision", facts.loadedConfigRevision ?: JSONObject.NULL)
        .put("notificationPermission", facts.notificationPermission)
        .put("observedAtMillis", facts.observedAtMillis)
        .put("platformSessionId", facts.platformSessionId)
        .put("protectedSocketCount", facts.protectedSocketCount)
        .put("publicRequestObserved", facts.publicRequestObserved)
        .put("recoveryEvidence", facts.recoveryEvidence)
        .put("routesApplied", facts.routesApplied)
        .put("serviceForeground", facts.serviceForeground)
        .put("tunEstablished", facts.tunEstablished)
        .put("validatedConfigDigest", facts.validatedConfigDigest ?: JSONObject.NULL)
        .put("validatedConfigRevision", facts.validatedConfigRevision ?: JSONObject.NULL)
        .put("vpnPermission", facts.vpnPermission)
}
