[package]
name = "mish-mobile"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
mish-settings = { path = "../../../crates/settings" }
serde = { version = "1.0.228", features = ["derive"] }
tauri = { version = "2.11.5", features = [] }
tauri-plugin-mish-vpn = { path = "plugins/mish-vpn" }

[features]
default = []
custom-protocol = ["tauri/custom-protocol"]
