import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";

const root = new URL("..", import.meta.url).pathname;
const sourcePath = `${root}/packages/bridge-protocol/bridge-protocol.json`;

interface BridgeProtocolSource {
  schemaVersion: number;
  protocolVersion: number;
  minimumClientProtocolVersion: number;
  minimumBackendProtocolVersion: number;
  compatibilityOutcomes: string[];
  capabilityFields: {
    statusCommands: string[];
    trafficCommands: string[];
  };
  publicMethods: string[];
  mockImplementedMethods: string[];
}

const source = JSON.parse(readFileSync(sourcePath, "utf8")) as BridgeProtocolSource;

function requirePositiveInteger(value: number, label: string) {
  if (!Number.isInteger(value) || value < 1) throw new Error(`${label} must be a positive integer`);
}

function requireSortedUnique(values: string[], label: string) {
  const expected = [...new Set(values)].sort();
  if (JSON.stringify(values) !== JSON.stringify(expected)) {
    throw new Error(`${label} must be sorted and contain no duplicates`);
  }
}

if (source.schemaVersion !== 1) throw new Error("Unsupported bridge protocol source schema");
requirePositiveInteger(source.protocolVersion, "protocolVersion");
requirePositiveInteger(source.minimumClientProtocolVersion, "minimumClientProtocolVersion");
requirePositiveInteger(source.minimumBackendProtocolVersion, "minimumBackendProtocolVersion");
if (source.minimumClientProtocolVersion > source.protocolVersion) {
  throw new Error("minimumClientProtocolVersion cannot exceed protocolVersion");
}
if (source.minimumBackendProtocolVersion > source.protocolVersion) {
  throw new Error("minimumBackendProtocolVersion cannot exceed protocolVersion");
}
if (
  JSON.stringify(source.compatibilityOutcomes) !==
  JSON.stringify(["compatible", "client-too-old", "backend-too-old"])
) {
  throw new Error("Bridge compatibility outcomes are a closed ordered contract");
}
requireSortedUnique(source.capabilityFields.statusCommands, "status command capability fields");
requireSortedUnique(source.capabilityFields.trafficCommands, "traffic command capability fields");
requireSortedUnique(source.publicMethods, "publicMethods");
requireSortedUnique(source.mockImplementedMethods, "mockImplementedMethods");
for (const method of source.mockImplementedMethods) {
  if (!source.publicMethods.includes(method)) {
    throw new Error(`Mock method ${method} is not public`);
  }
}

const mockUnavailableMethods = source.publicMethods.filter(
  (method) => !source.mockImplementedMethods.includes(method),
);
const ts = `// Generated by scripts/generate-bridge-protocol.ts; do not edit.
import * as z from "zod";

export const BRIDGE_PROTOCOL_VERSION = ${source.protocolVersion} as const;
export const BRIDGE_MINIMUM_CLIENT_PROTOCOL_VERSION = ${source.minimumClientProtocolVersion} as const;
export const BRIDGE_MINIMUM_BACKEND_PROTOCOL_VERSION = ${source.minimumBackendProtocolVersion} as const;
export const BRIDGE_PROTOCOL_COMPATIBILITY_OUTCOMES = ${JSON.stringify(source.compatibilityOutcomes)} as const;
export const BridgeProtocolCompatibilitySchema = z.enum(BRIDGE_PROTOCOL_COMPATIBILITY_OUTCOMES);
export type BridgeProtocolCompatibility = z.infer<typeof BridgeProtocolCompatibilitySchema>;
export const BRIDGE_STATUS_COMMAND_CAPABILITY_FIELDS = ${JSON.stringify(source.capabilityFields.statusCommands)} as const;
export const BRIDGE_TRAFFIC_COMMAND_CAPABILITY_FIELDS = ${JSON.stringify(source.capabilityFields.trafficCommands)} as const;
export const BRIDGE_PUBLIC_RPC_METHODS = ${JSON.stringify(source.publicMethods)} as const;
export const BRIDGE_MOCK_IMPLEMENTED_RPC_METHODS = ${JSON.stringify(source.mockImplementedMethods)} as const;
export const BRIDGE_MOCK_UNAVAILABLE_RPC_METHODS = ${JSON.stringify(mockUnavailableMethods)} as const;
export const BRIDGE_INFO_REQUEST = { clientProtocolVersion: BRIDGE_PROTOCOL_VERSION } as const;
`;

function rustStrings(values: string[]) {
  return values.map((value) => `    ${JSON.stringify(value)},`).join("\n");
}

const rust = `// Generated by scripts/generate-bridge-protocol.ts; do not edit.

pub const BRIDGE_PROTOCOL_VERSION: u32 = ${source.protocolVersion};
pub const BRIDGE_MINIMUM_CLIENT_PROTOCOL_VERSION: u32 = ${source.minimumClientProtocolVersion};
pub const BRIDGE_MINIMUM_BACKEND_PROTOCOL_VERSION: u32 = ${source.minimumBackendProtocolVersion};
pub const BRIDGE_PROTOCOL_COMPATIBILITY_OUTCOMES: &[&str] = &[
${rustStrings(source.compatibilityOutcomes)}
];
pub const BRIDGE_STATUS_COMMAND_CAPABILITY_FIELDS: &[&str] = &[
${rustStrings(source.capabilityFields.statusCommands)}
];
pub const BRIDGE_TRAFFIC_COMMAND_CAPABILITY_FIELDS: &[&str] = &[
${rustStrings(source.capabilityFields.trafficCommands)}
];
pub const BRIDGE_PUBLIC_RPC_METHODS: &[&str] = &[
${rustStrings(source.publicMethods)}
];

pub const fn compatibility_for_client(client_protocol_version: u32) -> &'static str {
    if client_protocol_version < BRIDGE_MINIMUM_CLIENT_PROTOCOL_VERSION {
        "client-too-old"
    } else if client_protocol_version > BRIDGE_PROTOCOL_VERSION {
        "backend-too-old"
    } else {
        "compatible"
    }
}
`;

mkdirSync(`${root}/packages/contracts/src/generated`, { recursive: true });
mkdirSync(`${root}/crates/desktop-bridge/src/generated`, { recursive: true });
writeFileSync(`${root}/packages/contracts/src/generated/bridge-protocol.ts`, ts);
writeFileSync(`${root}/crates/desktop-bridge/src/generated/bridge_protocol.rs`, rust);

for (const [command, args] of [
  ["rustfmt", ["--edition", "2024", "crates/desktop-bridge/src/generated/bridge_protocol.rs"]],
  ["pnpm", ["exec", "oxfmt", "--write", "packages/contracts/src/generated/bridge-protocol.ts"]],
] as const) {
  const result = spawnSync(command, args, { cwd: root, stdio: "inherit" });
  if (result.status !== 0) process.exit(result.status ?? 1);
}
