import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";

const root = new URL("..", import.meta.url).pathname;
const sourcePath = `${root}/packages/android-platform-facts/android-platform-facts.json`;

interface PlatformFactsSource {
  schemaVersion: number;
  factsVersion: number;
  safeIntegerMax: number;
  identifierMaxLength: number;
  eventKinds: string[];
  failureKinds: string[];
  recoveryEvidence: string[];
  vpnPermissions: string[];
  notificationPermissions: string[];
  availability: string[];
  coreConfigStates: string[];
  factFields: string[];
  lifecycleAuthorityFields: string[];
  bounds: {
    coreCommitMinLength: number;
    coreCommitMaxLength: number;
    coreVersionMaxLength: number;
    coreWrapperRevisionMaxLength: number;
    protectedSocketCountMax: number;
  };
  goldenFacts: Record<string, unknown>;
}

const source = JSON.parse(readFileSync(sourcePath, "utf8")) as PlatformFactsSource;

function requirePositiveInteger(value: number, label: string): void {
  if (!Number.isSafeInteger(value) || value < 1) {
    throw new Error(`${label} must be a positive safe integer`);
  }
}

function requireSortedUnique(values: string[], label: string): void {
  const expected = [...new Set(values)].sort();
  if (JSON.stringify(values) !== JSON.stringify(expected)) {
    throw new Error(`${label} must be sorted and contain no duplicates`);
  }
}

if (source.schemaVersion !== 1) throw new Error("Unsupported Android platform-facts schema");
requirePositiveInteger(source.factsVersion, "factsVersion");
requirePositiveInteger(source.safeIntegerMax, "safeIntegerMax");
requirePositiveInteger(source.identifierMaxLength, "identifierMaxLength");
for (const [label, values] of [
  ["eventKinds", source.eventKinds],
  ["failureKinds", source.failureKinds],
  ["recoveryEvidence", source.recoveryEvidence],
  ["vpnPermissions", source.vpnPermissions],
  ["notificationPermissions", source.notificationPermissions],
  ["availability", source.availability],
  ["coreConfigStates", source.coreConfigStates],
  ["factFields", source.factFields],
  ["lifecycleAuthorityFields", source.lifecycleAuthorityFields],
] as const) {
  requireSortedUnique(values, label);
}
if (JSON.stringify(Object.keys(source.goldenFacts).sort()) !== JSON.stringify(source.factFields)) {
  throw new Error("goldenFacts must contain every platform-facts field exactly once");
}

function pascalCase(value: string): string {
  return value
    .split("-")
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}

function rustEnum(name: string, values: string[]): string {
  const variants = values.map((value) => `    ${pascalCase(value)},`).join("\n");
  const arms = values
    .map((value) => `            Self::${pascalCase(value)} => ${JSON.stringify(value)},`)
    .join("\n");
  const fromArms = values
    .map((value) => `            ${JSON.stringify(value)} => Self::${pascalCase(value)},`)
    .join("\n");
  return `#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub(crate) enum ${name} {
${variants}
}

impl ${name} {
    pub(crate) const fn wire_name(self) -> &'static str {
        match self {
${arms}
        }
    }
}

impl From<&str> for ${name} {
    fn from(value: &str) -> Self {
        match value {
${fromArms}
            _ => panic!("unknown ${name} wire value: {value}"),
        }
    }
}

impl PartialEq<&str> for ${name} {
    fn eq(&self, other: &&str) -> bool {
        self.wire_name() == *other
    }
}
`;
}

const rust = `// Generated by scripts/generate-android-platform-facts.ts; do not edit.
use serde::{Deserialize, Serialize};

pub(crate) const ANDROID_PLATFORM_FACTS_VERSION: u8 = ${source.factsVersion};
pub(crate) const ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX: u64 = ${source.safeIntegerMax};
#[cfg(test)]
pub(crate) const ANDROID_PLATFORM_FACTS_GOLDEN_JSON: &str = r#"${JSON.stringify(source.goldenFacts)}"#;

${rustEnum("PlatformEventKind", source.eventKinds)}
${rustEnum("PlatformFailureKind", source.failureKinds)}
${rustEnum("PlatformRecoveryEvidence", source.recoveryEvidence)}
${rustEnum("VpnPermission", source.vpnPermissions)}
${rustEnum("NotificationPermission", source.notificationPermissions)}
${rustEnum("PlatformAvailability", source.availability)}
${rustEnum("CoreConfigState", source.coreConfigStates)}
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct PlatformLifecycleAuthority {
    pub machine_authority: String,
    pub scope_epoch: u64,
    pub operation_id: String,
    pub admitted_revision: u64,
    pub effect_identity: String,
}

impl PlatformLifecycleAuthority {
    pub(crate) fn valid(&self) -> bool {
        valid_identifier(&self.machine_authority)
            && (1..=ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX).contains(&self.scope_epoch)
            && valid_identifier(&self.operation_id)
            && (1..=ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX).contains(&self.admitted_revision)
            && self.effect_identity.parse::<u64>().is_ok_and(|effect| {
                (1..=ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX).contains(&effect)
            })
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct PlatformFacts {
    #[serde(deserialize_with = "deserialize_required_option")]
    pub activation_failure: Option<PlatformFailureKind>,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub activation_session_id: Option<String>,
    pub active_network: bool,
    pub config_failure_injection_available: bool,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub core_abi_version: Option<u8>,
    pub core_availability: PlatformAvailability,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub core_commit: Option<String>,
    pub core_config_state: CoreConfigState,
    pub core_running: bool,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub core_version: Option<String>,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub core_wrapper_revision: Option<String>,
    pub dns_applied: bool,
    pub event: PlatformEventKind,
    pub fact_sequence: u64,
    pub facts_version: u8,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub lifecycle_authority: Option<PlatformLifecycleAuthority>,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub loaded_config_digest: Option<String>,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub loaded_config_revision: Option<String>,
    pub notification_permission: NotificationPermission,
    pub observed_at_millis: u64,
    pub platform_session_id: String,
    pub protected_socket_count: u64,
    pub public_request_observed: bool,
    pub recovery_evidence: PlatformRecoveryEvidence,
    pub routes_applied: bool,
    pub service_foreground: bool,
    pub tun_established: bool,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub validated_config_digest: Option<String>,
    #[serde(deserialize_with = "deserialize_required_option")]
    pub validated_config_revision: Option<String>,
    pub vpn_permission: VpnPermission,
}

fn deserialize_required_option<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Deserialize<'de>,
{
    Option::<T>::deserialize(deserializer)
}

impl PlatformFacts {
    pub(crate) fn validate(&self) -> Result<(), &'static str> {
        if self.facts_version != ANDROID_PLATFORM_FACTS_VERSION {
            return Err("unsupported factsVersion");
        }
        if !(1..=ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX).contains(&self.fact_sequence) {
            return Err("factSequence is outside the wire integer bound");
        }
        if self.observed_at_millis > ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX {
            return Err("observedAtMillis is outside the wire integer bound");
        }
        if !valid_identifier(&self.platform_session_id)
            || !valid_optional_identifier(&self.activation_session_id, ${source.identifierMaxLength})
            || !valid_optional_identifier(&self.loaded_config_revision, ${source.identifierMaxLength})
            || !valid_optional_identifier(&self.validated_config_revision, ${source.identifierMaxLength})
        {
            return Err("platform fact identity is invalid");
        }
        if self.protected_socket_count > ${source.bounds.protectedSocketCountMax} {
            return Err("protectedSocketCount exceeds its bound");
        }
        if self.core_abi_version.is_some_and(|version| version != 1)
            || !valid_optional_core_commit(&self.core_commit)
            || !valid_optional_wire_text(&self.core_version, ${source.bounds.coreVersionMaxLength})
            || !valid_optional_identifier(&self.core_wrapper_revision, ${source.bounds.coreWrapperRevisionMaxLength})
        {
            return Err("Mobile Core identity is invalid");
        }
        let core_identity_complete = self.core_abi_version.is_some()
            && self.core_commit.is_some()
            && self.core_version.is_some()
            && self.core_wrapper_revision.is_some();
        if (self.core_availability == PlatformAvailability::Available) != core_identity_complete {
            return Err("Mobile Core availability and identity disagree");
        }
        if !valid_optional_digest(&self.loaded_config_digest)
            || !valid_optional_digest(&self.validated_config_digest)
        {
            return Err("configuration digest is invalid");
        }
        let loaded_complete = self.loaded_config_digest.is_some() && self.loaded_config_revision.is_some();
        if (self.core_config_state == CoreConfigState::Loaded) != loaded_complete {
            return Err("loaded configuration identity is inconsistent");
        }
        if self.validated_config_digest.is_some() != self.validated_config_revision.is_some() {
            return Err("validated configuration identity is incomplete");
        }
        if self.lifecycle_authority.as_ref().is_some_and(|authority| !authority.valid()) {
            return Err("lifecycleAuthority is invalid");
        }
        Ok(())
    }
}

fn valid_identifier(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= ${source.identifierMaxLength}
        && value.bytes().all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
}

fn valid_optional_identifier(value: &Option<String>, max: usize) -> bool {
    value.as_ref().is_none_or(|value| !value.is_empty() && value.len() <= max && valid_identifier(value))
}

fn valid_optional_core_commit(value: &Option<String>) -> bool {
    value.as_ref().is_none_or(|value| {
        (${source.bounds.coreCommitMinLength}..=${source.bounds.coreCommitMaxLength}).contains(&value.len())
            && value.bytes().all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
    })
}

fn valid_optional_wire_text(value: &Option<String>, max: usize) -> bool {
    value.as_ref().is_none_or(|value| {
        !value.is_empty()
            && value.len() <= max
            && value.bytes().all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.' | b'+'))
    })
}

fn valid_optional_digest(value: &Option<String>) -> bool {
    value.as_ref().is_none_or(|value| value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase()))
}
`;

function tsValues(values: string[]): string {
  return JSON.stringify(values);
}

const ts = `// Generated by scripts/generate-android-platform-facts.ts; do not edit.
import * as z from "zod";

export const ANDROID_PLATFORM_FACTS_VERSION = ${source.factsVersion} as const;
export const ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX = ${source.safeIntegerMax} as const;
export const ANDROID_PLATFORM_EVENT_KINDS = ${tsValues(source.eventKinds)} as const;
export const ANDROID_PLATFORM_FAILURE_KINDS = ${tsValues(source.failureKinds)} as const;
export const ANDROID_PLATFORM_RECOVERY_EVIDENCE = ${tsValues(source.recoveryEvidence)} as const;
export const ANDROID_VPN_PERMISSIONS = ${tsValues(source.vpnPermissions)} as const;
export const ANDROID_NOTIFICATION_PERMISSIONS = ${tsValues(source.notificationPermissions)} as const;
export const ANDROID_PLATFORM_AVAILABILITY = ${tsValues(source.availability)} as const;
export const ANDROID_CORE_CONFIG_STATES = ${tsValues(source.coreConfigStates)} as const;
export const ANDROID_PLATFORM_FACT_FIELDS = ${tsValues(source.factFields)} as const;
export const ANDROID_PLATFORM_LIFECYCLE_AUTHORITY_FIELDS = ${tsValues(source.lifecycleAuthorityFields)} as const;
export const ANDROID_PLATFORM_FACTS_GOLDEN = ${JSON.stringify(source.goldenFacts)} as const;

export const AndroidPlatformEventKindSchema = z.enum(ANDROID_PLATFORM_EVENT_KINDS);
export const AndroidPlatformFailureKindSchema = z.enum(ANDROID_PLATFORM_FAILURE_KINDS);
export const AndroidPlatformRecoveryEvidenceSchema = z.enum(ANDROID_PLATFORM_RECOVERY_EVIDENCE);
export const AndroidVpnPermissionSchema = z.enum(ANDROID_VPN_PERMISSIONS);
export const AndroidNotificationPermissionSchema = z.enum(ANDROID_NOTIFICATION_PERMISSIONS);
export const AndroidPlatformAvailabilitySchema = z.enum(ANDROID_PLATFORM_AVAILABILITY);
export const AndroidCoreConfigStateSchema = z.enum(ANDROID_CORE_CONFIG_STATES);
const IdentifierSchema = z.string().regex(/^[A-Za-z0-9._-]{1,${source.identifierMaxLength}}$/u);
const DigestSchema = z.string().regex(/^[0-9a-f]{64}$/u);
const WireIntegerSchema = z.number().int().nonnegative().max(ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX);

export const AndroidPlatformLifecycleAuthoritySchema = z
  .object({
    admittedRevision: WireIntegerSchema.positive(),
    effectIdentity: z.string().regex(/^[1-9][0-9]*$/u).max(16),
    machineAuthority: IdentifierSchema,
    operationId: IdentifierSchema,
    scopeEpoch: WireIntegerSchema.positive(),
  })
  .strict();

export const AndroidPlatformFactsSchema = z
  .object({
    activationFailure: AndroidPlatformFailureKindSchema.nullable(),
    activationSessionId: IdentifierSchema.nullable(),
    activeNetwork: z.boolean(),
    configFailureInjectionAvailable: z.boolean(),
    coreAbiVersion: z.literal(1).nullable(),
    coreAvailability: AndroidPlatformAvailabilitySchema,
    coreCommit: z.string().regex(/^[0-9a-f]{${source.bounds.coreCommitMinLength},${source.bounds.coreCommitMaxLength}}$/u).nullable(),
    coreConfigState: AndroidCoreConfigStateSchema,
    coreRunning: z.boolean(),
    coreVersion: z.string().regex(/^[A-Za-z0-9._+-]{1,${source.bounds.coreVersionMaxLength}}$/u).nullable(),
    coreWrapperRevision: z.string().regex(/^[A-Za-z0-9._-]{1,${source.bounds.coreWrapperRevisionMaxLength}}$/u).nullable(),
    dnsApplied: z.boolean(),
    event: AndroidPlatformEventKindSchema,
    factSequence: WireIntegerSchema.positive(),
    factsVersion: z.literal(ANDROID_PLATFORM_FACTS_VERSION),
    lifecycleAuthority: AndroidPlatformLifecycleAuthoritySchema.nullable(),
    loadedConfigDigest: DigestSchema.nullable(),
    loadedConfigRevision: IdentifierSchema.nullable(),
    notificationPermission: AndroidNotificationPermissionSchema,
    observedAtMillis: WireIntegerSchema,
    platformSessionId: IdentifierSchema,
    protectedSocketCount: WireIntegerSchema.max(${source.bounds.protectedSocketCountMax}),
    publicRequestObserved: z.boolean(),
    recoveryEvidence: AndroidPlatformRecoveryEvidenceSchema,
    routesApplied: z.boolean(),
    serviceForeground: z.boolean(),
    tunEstablished: z.boolean(),
    validatedConfigDigest: DigestSchema.nullable(),
    validatedConfigRevision: IdentifierSchema.nullable(),
    vpnPermission: AndroidVpnPermissionSchema,
  })
  .strict()
  .superRefine((facts, context) => {
    const coreIdentity = [facts.coreAbiVersion, facts.coreCommit, facts.coreVersion, facts.coreWrapperRevision];
    if ((facts.coreAvailability === "available") !== coreIdentity.every((value) => value !== null)) {
      context.addIssue({ code: "custom", message: "Mobile Core availability and identity disagree", path: ["coreAvailability"] });
    }
    const loadedComplete = facts.loadedConfigDigest !== null && facts.loadedConfigRevision !== null;
    if ((facts.coreConfigState === "loaded") !== loadedComplete) {
      context.addIssue({ code: "custom", message: "Loaded configuration identity is inconsistent", path: ["coreConfigState"] });
    }
    if ((facts.validatedConfigDigest === null) !== (facts.validatedConfigRevision === null)) {
      context.addIssue({ code: "custom", message: "Validated configuration identity is incomplete", path: ["validatedConfigDigest"] });
    }
  });
export interface AndroidPlatformFactsDto extends z.infer<typeof AndroidPlatformFactsSchema> {}
`;

function kotlinEnum(name: string, values: string[]): string {
  return `internal enum class ${name}(val wireName: String) {\n${values
    .map((value) => `    ${value.replaceAll("-", "_").toUpperCase()}(${JSON.stringify(value)}),`)
    .join("\n")}\n}`;
}

const kotlin = `// Generated by scripts/generate-android-platform-facts.ts; do not edit.
package com.asuka109.mish.vpn

import org.json.JSONObject

internal const val ANDROID_PLATFORM_FACTS_VERSION = ${source.factsVersion}
internal const val ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX = ${source.safeIntegerMax}L
internal const val ANDROID_PLATFORM_FACTS_GOLDEN_JSON = ${JSON.stringify(JSON.stringify(source.goldenFacts))}

${kotlinEnum("PlatformEventKind", source.eventKinds)}

${kotlinEnum("PlatformFailureKind", source.failureKinds)}

${kotlinEnum("PlatformRecoveryEvidence", source.recoveryEvidence)}

private val VPN_PERMISSIONS = setOf(${source.vpnPermissions.map(JSON.stringify).join(", ")})
private val NOTIFICATION_PERMISSIONS = setOf(${source.notificationPermissions.map(JSON.stringify).join(", ")})
private val PLATFORM_AVAILABILITY = setOf(${source.availability.map(JSON.stringify).join(", ")})
private val CORE_CONFIG_STATES = setOf(${source.coreConfigStates.map(JSON.stringify).join(", ")})
private val IDENTIFIER_PATTERN = Regex("^[A-Za-z0-9._-]{1,${source.identifierMaxLength}}$")
private val DIGEST_PATTERN = Regex("^[0-9a-f]{64}$")
private val CORE_COMMIT_PATTERN = Regex("^[0-9a-f]{${source.bounds.coreCommitMinLength},${source.bounds.coreCommitMaxLength}}$")
private val CORE_VERSION_PATTERN = Regex("^[A-Za-z0-9._+-]{1,${source.bounds.coreVersionMaxLength}}$")
private val CORE_WRAPPER_PATTERN = Regex("^[A-Za-z0-9._-]{1,${source.bounds.coreWrapperRevisionMaxLength}}$")

internal fun validatePlatformFacts(facts: MobilePlatformFacts) {
    check(facts.factsVersion == ANDROID_PLATFORM_FACTS_VERSION) { "Unsupported factsVersion" }
    check(facts.factSequence in 1..ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX) { "Invalid factSequence" }
    check(facts.observedAtMillis in 0..ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX) { "Invalid observedAtMillis" }
    check(facts.platformSessionId.matches(IDENTIFIER_PATTERN)) { "Invalid platformSessionId" }
    check(facts.activationSessionId == null || facts.activationSessionId.matches(IDENTIFIER_PATTERN)) { "Invalid activationSessionId" }
    check(facts.event in PlatformEventKind.entries.map { it.wireName }) { "Unknown platform event" }
    check(facts.activationFailure == null || facts.activationFailure in PlatformFailureKind.entries.map { it.wireName }) { "Unknown platform failure" }
    check(facts.recoveryEvidence in PlatformRecoveryEvidence.entries.map { it.wireName }) { "Unknown recovery evidence" }
    check(facts.vpnPermission in VPN_PERMISSIONS) { "Unknown VPN permission" }
    check(facts.notificationPermission in NOTIFICATION_PERMISSIONS) { "Unknown notification permission" }
    check(facts.coreAvailability in PLATFORM_AVAILABILITY) { "Unknown Core availability" }
    check(facts.coreConfigState in CORE_CONFIG_STATES) { "Unknown Core configuration state" }
    check(facts.protectedSocketCount in 0..${source.bounds.protectedSocketCountMax}L) { "Invalid protectedSocketCount" }
    check(facts.coreAbiVersion == null || facts.coreAbiVersion == 1) { "Invalid Core ABI version" }
    check(facts.coreCommit == null || facts.coreCommit.matches(CORE_COMMIT_PATTERN)) { "Invalid Core commit" }
    check(facts.coreVersion == null || facts.coreVersion.matches(CORE_VERSION_PATTERN)) { "Invalid Core version" }
    check(facts.coreWrapperRevision == null || facts.coreWrapperRevision.matches(CORE_WRAPPER_PATTERN)) { "Invalid Core wrapper revision" }
    val coreIdentityComplete = facts.coreAbiVersion != null && facts.coreCommit != null && facts.coreVersion != null && facts.coreWrapperRevision != null
    check((facts.coreAvailability == "available") == coreIdentityComplete) { "Core availability and identity disagree" }
    check(facts.loadedConfigDigest == null || facts.loadedConfigDigest.matches(DIGEST_PATTERN)) { "Invalid loaded digest" }
    check(facts.validatedConfigDigest == null || facts.validatedConfigDigest.matches(DIGEST_PATTERN)) { "Invalid validated digest" }
    check(facts.loadedConfigRevision == null || facts.loadedConfigRevision.matches(IDENTIFIER_PATTERN)) { "Invalid loaded revision" }
    check(facts.validatedConfigRevision == null || facts.validatedConfigRevision.matches(IDENTIFIER_PATTERN)) { "Invalid validated revision" }
    val loadedComplete = facts.loadedConfigDigest != null && facts.loadedConfigRevision != null
    check((facts.coreConfigState == "loaded") == loadedComplete) { "Loaded configuration identity is inconsistent" }
    check((facts.validatedConfigDigest == null) == (facts.validatedConfigRevision == null)) { "Validated configuration identity is incomplete" }
    check(facts.lifecycleAuthority == null || (
        facts.lifecycleAuthority.isValid() &&
            facts.lifecycleAuthority.scopeEpoch <= ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX &&
            facts.lifecycleAuthority.admittedRevision <= ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX &&
            facts.lifecycleAuthority.effectIdentity.toLongOrNull()?.let { it in 1..ANDROID_PLATFORM_FACTS_SAFE_INTEGER_MAX } == true
    )) { "Invalid lifecycle authority" }
}

internal fun platformFactsToJson(facts: MobilePlatformFacts): JSONObject {
    validatePlatformFacts(facts)
    return JSONObject()
        .put("activationFailure", facts.activationFailure ?: JSONObject.NULL)
        .put("activationSessionId", facts.activationSessionId ?: JSONObject.NULL)
        .put("activeNetwork", facts.activeNetwork)
        .put("configFailureInjectionAvailable", facts.configFailureInjectionAvailable)
        .put("coreAbiVersion", facts.coreAbiVersion ?: JSONObject.NULL)
        .put("coreAvailability", facts.coreAvailability)
        .put("coreCommit", facts.coreCommit ?: JSONObject.NULL)
        .put("coreConfigState", facts.coreConfigState)
        .put("coreRunning", facts.coreRunning)
        .put("coreVersion", facts.coreVersion ?: JSONObject.NULL)
        .put("coreWrapperRevision", facts.coreWrapperRevision ?: JSONObject.NULL)
        .put("dnsApplied", facts.dnsApplied)
        .put("event", facts.event)
        .put("factSequence", facts.factSequence)
        .put("factsVersion", facts.factsVersion)
        .put("lifecycleAuthority", facts.lifecycleAuthority?.toJson() ?: JSONObject.NULL)
        .put("loadedConfigDigest", facts.loadedConfigDigest ?: JSONObject.NULL)
        .put("loadedConfigRevision", facts.loadedConfigRevision ?: JSONObject.NULL)
        .put("notificationPermission", facts.notificationPermission)
        .put("observedAtMillis", facts.observedAtMillis)
        .put("platformSessionId", facts.platformSessionId)
        .put("protectedSocketCount", facts.protectedSocketCount)
        .put("publicRequestObserved", facts.publicRequestObserved)
        .put("recoveryEvidence", facts.recoveryEvidence)
        .put("routesApplied", facts.routesApplied)
        .put("serviceForeground", facts.serviceForeground)
        .put("tunEstablished", facts.tunEstablished)
        .put("validatedConfigDigest", facts.validatedConfigDigest ?: JSONObject.NULL)
        .put("validatedConfigRevision", facts.validatedConfigRevision ?: JSONObject.NULL)
        .put("vpnPermission", facts.vpnPermission)
}
`;

const outputs = [
  ["packages/contracts/src/generated/android-platform-facts.ts", ts],
  ["apps/mobile/src-tauri/plugins/mish-vpn/src/generated/platform_facts.rs", rust],
  [
    "apps/mobile/src-tauri/plugins/mish-vpn/android/src/main/java/com/asuka109/mish/vpn/AndroidPlatformFactsContract.kt",
    kotlin,
  ],
] as const;
for (const [path, contents] of outputs) {
  mkdirSync(`${root}/${path.slice(0, path.lastIndexOf("/"))}`, { recursive: true });
  writeFileSync(`${root}/${path}`, contents);
}

for (const [command, args] of [
  ["rustfmt", ["--edition", "2024", outputs[1][0]]],
  ["pnpm", ["exec", "oxfmt", "--write", outputs[0][0]]],
] as const) {
  const result = spawnSync(command, args, { cwd: root, stdio: "inherit" });
  if (result.status !== 0) process.exit(result.status ?? 1);
}
