import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const schema = JSON.parse(
  readFileSync(`${root}/packages/presentation-schema/presentation.schema.json`, "utf8"),
);
const rustEnum = (value: string) =>
  value
    .split(/[.-]/)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
const messages = Object.entries(schema.messages) as [string, { args?: Record<string, "string"> }][];
const messageIds = messages.map(([id]) => id);
const rustMessageVariants = messages
  .map(([id, definition]) => {
    const name = rustEnum(id);
    const args = Object.keys(definition.args ?? {});
    return args.length === 0
      ? `    ${name},`
      : `    ${name} { ${args.map((arg) => `${arg}: &'a str`).join(", ")} },`;
  })
  .join("\n");
const rustIdArms = messages
  .map(([id]) => `            Self::${rustEnum(id)} => ${JSON.stringify(id)},`)
  .join("\n");
const rustMessageIdArms = messages
  .map(([id, definition]) => {
    const name = rustEnum(id);
    const pattern =
      Object.keys(definition.args ?? {}).length === 0 ? `Self::${name}` : `Self::${name} { .. }`;
    return `            ${pattern} => NativeMessageId::${name},`;
  })
  .join("\n");
const rustActionArms = schema.actions
  .map((id: string) => `            Self::${rustEnum(id)} => ${JSON.stringify(id)},`)
  .join("\n");
const tsMessageVariants = messages
  .map(([id, definition]) => {
    const fields = Object.keys(definition.args ?? {})
      .map((arg) => `${arg}: string`)
      .join("; ");
    return `  | { id: ${JSON.stringify(id)}${fields ? `; ${fields}` : ""} }`;
  })
  .join("\n");
const tsArgs = messages
  .map(([id, definition]) => {
    const fields = Object.keys(definition.args ?? {})
      .map((arg) => `${arg}: string`)
      .join("; ");
    return `  ${JSON.stringify(id)}: { ${fields} };`;
  })
  .join("\n");
mkdirSync(`${root}/packages/contracts/src/generated`, { recursive: true });
mkdirSync(`${root}/crates/presentation-contract/src`, { recursive: true });
const ts = `// Generated by scripts/generate-presentation-contract.ts; do not edit.\nexport const presentationLocales = ${JSON.stringify(schema.locales)} as const;\nexport type PresentationLocale = (typeof presentationLocales)[number];\nexport const nativeMessageIds = ${JSON.stringify(messageIds)} as const;\nexport type NativeMessageId = (typeof nativeMessageIds)[number];\nexport const nativeActionIds = ${JSON.stringify(schema.actions)} as const;\nexport type NativeActionId = (typeof nativeActionIds)[number];\n\nexport type NativeMessageArgs = {\n${tsArgs}\n};\n\nexport type NativeMessage =\n${tsMessageVariants};\n`;
const rust = `// Generated by scripts/generate-presentation-contract.ts; do not edit.\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum Locale {\n    En,\n    ZhCn,\n}\nimpl Locale {\n    pub const ALL: [Self; 2] = [Self::En, Self::ZhCn];\n    pub const fn as_str(self) -> &'static str {\n        match self {\n            Self::En => \"en\",\n            Self::ZhCn => \"zh-CN\",\n        }\n    }\n}\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum NativeMessageId {\n${messageIds.map((id: string) => `    ${rustEnum(id)},`).join("\n")}\n}\nimpl NativeMessageId {\n    pub const fn as_str(self) -> &'static str {\n        match self {\n${rustIdArms}\n        }\n    }\n}\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum NativeMessage<'a> {\n${rustMessageVariants}\n}\nimpl NativeMessage<'_> {\n    pub const fn id(self) -> NativeMessageId {\n        match self {\n${rustMessageIdArms}\n        }\n    }\n}\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum NativeActionId {\n${schema.actions.map((id: string) => `    ${rustEnum(id)},`).join("\n")}\n}\nimpl NativeActionId {\n    pub const fn as_str(self) -> &'static str {\n        match self {\n${rustActionArms}\n        }\n    }\n}\n`;
writeFileSync(`${root}/packages/contracts/src/generated/presentation.ts`, ts);
writeFileSync(`${root}/crates/presentation-contract/src/generated.rs`, rust);
for (const [command, args] of [
  ["rustfmt", ["--edition", "2024", "crates/presentation-contract/src/generated.rs"]],
  ["pnpm", ["exec", "oxfmt", "--write", "packages/contracts/src/generated/presentation.ts"]],
] as const) {
  const result = spawnSync(command, args, { cwd: root, stdio: "inherit" });
  if (result.status !== 0) process.exit(result.status ?? 1);
}
