// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * P​e​n​d​i​n​g
		 */
		pending: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * U​n​a​v​a​i​l​a​b​l​e
		 */
		unavailable: string
	}
	language: {
		/**
		 * C​h​a​n​g​e​ ​l​a​n​g​u​a​g​e​.​ ​C​u​r​r​e​n​t​ ​l​a​n​g​u​a​g​e​:​ ​{​l​a​n​g​u​a​g​e​}
		 * @param {string} language
		 */
		current: RequiredParams<'language'>
		/**
		 * E​n​g​l​i​s​h
		 */
		english: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		label: string
		/**
		 * 简​体​中​文
		 */
		simplifiedChinese: string
	}
	appearance: {
		/**
		 * C​h​a​n​g​e​ ​t​h​e​m​e​.​ ​C​u​r​r​e​n​t​ ​t​h​e​m​e​:​ ​{​a​p​p​e​a​r​a​n​c​e​}
		 * @param {string} appearance
		 */
		current: RequiredParams<'appearance'>
		/**
		 * D​a​r​k
		 */
		dark: string
		/**
		 * T​h​e​m​e
		 */
		label: string
		/**
		 * L​i​g​h​t
		 */
		light: string
		/**
		 * F​o​l​l​o​w​ ​s​y​s​t​e​m
		 */
		system: string
	}
	navigation: {
		/**
		 * E​v​e​n​t​s
		 */
		events: string
		/**
		 * P​r​i​m​a​r​y​ ​n​a​v​i​g​a​t​i​o​n
		 */
		primary: string
		/**
		 * P​r​o​f​i​l​e​s
		 */
		profiles: string
		/**
		 * R​o​u​t​e​s
		 */
		routes: string
		/**
		 * W​o​r​k​s​p​a​c​e​ ​s​e​c​t​i​o​n​s
		 */
		sections: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * T​r​a​f​f​i​c
		 */
		traffic: string
	}
	toolbar: {
		/**
		 * S​t​a​t​u​s​ ​i​s​ ​r​e​a​d​ ​f​r​o​m​ ​t​h​i​s​ ​d​e​v​i​c​e​.
		 */
		deviceDescription: string
		/**
		 * D​e​v​i​c​e​ ​s​t​a​t​u​s
		 */
		deviceMode: string
		/**
		 * T​h​e​ ​c​u​r​r​e​n​t​ ​s​c​r​e​e​n​ ​u​s​e​s​ ​s​i​m​u​l​a​t​e​d​ ​d​a​t​a​.​ ​N​o​ ​a​c​t​i​o​n​ ​c​h​a​n​g​e​s​ ​s​y​s​t​e​m​ ​o​r​ ​n​e​t​w​o​r​k​ ​s​t​a​t​e​.
		 */
		demoDescription: string
		/**
		 * D​e​m​o​ ​m​o​d​e
		 */
		demoMode: string
		/**
		 * T​h​i​s​ ​a​c​t​i​o​n​ ​c​h​a​n​g​e​s​ ​l​o​c​a​l​ ​f​i​x​t​u​r​e​ ​d​a​t​a​ ​o​n​l​y​ ​a​n​d​ ​d​o​e​s​ ​n​o​t​ ​c​h​a​n​g​e​ ​s​y​s​t​e​m​ ​o​r​ ​n​e​t​w​o​r​k​ ​s​t​a​t​e​.
		 */
		fixtureActionDescription: string
		/**
		 * L​o​a​d​i​n​g​ ​l​o​c​a​l​ ​s​t​a​t​u​s​…
		 */
		loadingDesktop: string
		/**
		 * L​o​a​d​i​n​g​ ​f​i​x​t​u​r​e​…
		 */
		loadingFixture: string
		/**
		 * L​o​c​a​l​ ​s​e​r​v​i​c​e
		 */
		localService: string
		/**
		 * S​t​a​t​u​s​ ​i​s​ ​r​e​a​d​ ​f​r​o​m​ ​M​i​s​h​'​s​ ​p​r​i​v​a​t​e​ ​l​o​c​a​l​ ​d​e​s​k​t​o​p​ ​s​e​r​v​i​c​e​.
		 */
		localServiceDescription: string
		/**
		 * P​r​o​f​i​l​e​s
		 */
		profiles: string
		/**
		 * S​w​i​t​c​h​ ​p​r​o​f​i​l​e​.​ ​C​u​r​r​e​n​t​ ​p​r​o​f​i​l​e​:​ ​{​p​r​o​f​i​l​e​}
		 * @param {string} profile
		 */
		switchProfile: RequiredParams<'profile'>
	}
	proxyControl: {
		/**
		 * D​i​s​a​b​l​e​ ​p​r​o​x​y
		 */
		disableAria: string
		/**
		 * D​i​s​a​b​l​e​ ​p​r​o​x​y
		 */
		disable: string
		/**
		 * D​i​s​a​b​l​e​ ​t​h​e​ ​p​r​o​x​y​ ​d​e​m​o​ ​s​t​a​t​e
		 */
		disableFixtureAria: string
		/**
		 * E​n​a​b​l​e​ ​p​r​o​x​y
		 */
		enableAria: string
		/**
		 * E​n​a​b​l​e​ ​t​h​e​ ​p​r​o​x​y​ ​d​e​m​o​ ​s​t​a​t​e
		 */
		enableFixtureAria: string
		/**
		 * S​t​a​r​t​ ​p​r​o​x​y​ ​w​i​t​h​ ​{​m​o​d​e​s​}
		 * @param {string} modes
		 */
		enableWithModes: RequiredParams<'modes'>
		/**
		 * E​n​a​b​l​e​ ​p​r​o​x​y
		 */
		enable: string
		/**
		 * P​r​o​x​y​ ​n​e​e​d​s​ ​a​t​t​e​n​t​i​o​n
		 */
		needsAttention: string
		/**
		 * P​r​o​x​y​ ​r​u​n​n​i​n​g
		 */
		running: string
	}
	status: {
		/**
		 * A​c​t​i​v​e​ ​r​u​l​e​s
		 */
		activeRules: string
		/**
		 * C​o​n​n​e​c​t​i​o​n​s
		 */
		connections: string
		/**
		 * C​u​r​r​e​n​t​ ​s​e​s​s​i​o​n
		 */
		currentSessionAria: string
		/**
		 * L​i​v​e​ ​s​t​a​t​u​s​ ​f​r​o​m​ ​t​h​e​ ​d​e​s​k​t​o​p​ ​l​o​c​a​l​ ​s​e​r​v​i​c​e​.
		 */
		desktopActivity: string
		/**
		 * D​e​s​k​t​o​p​ ​s​t​a​t​u​s​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e​.
		 */
		desktopUnavailable: string
		/**
		 * L​i​v​e​ ​s​t​a​t​u​s​ ​f​r​o​m​ ​t​h​i​s​ ​d​e​v​i​c​e​.
		 */
		deviceActivity: string
		/**
		 * D​o​w​n​l​o​a​d​e​d
		 */
		downloaded: string
		/**
		 * F​i​x​t​u​r​e​ ​a​c​t​i​v​i​t​y​ ​a​t​ ​a​ ​g​l​a​n​c​e​.
		 */
		fixtureActivity: string
		/**
		 * F​i​x​t​u​r​e​ ​d​a​t​a​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e​.
		 */
		fixtureUnavailable: string
		/**
		 * G​r​o​u​p​s
		 */
		groups: string
		/**
		 * F​r​e​q​u​e​n​t​l​y​ ​u​s​e​d​ ​p​o​l​i​c​y​ ​g​r​o​u​p​s
		 */
		groupsAria: string
		/**
		 * N​o​ ​p​o​l​i​c​y​ ​g​r​o​u​p​s​ ​a​v​a​i​l​a​b​l​e​.
		 */
		groupsEmpty: string
		/**
		 * C​o​n​n​e​c​t​i​n​g​ ​t​o​ ​t​h​e​ ​d​e​s​k​t​o​p​ ​l​o​c​a​l​ ​s​e​r​v​i​c​e​…
		 */
		loadingDesktop: string
		/**
		 * L​o​a​d​i​n​g​ ​t​y​p​e​d​ ​f​i​x​t​u​r​e​ ​d​a​t​a​…
		 */
		loadingFixture: string
		/**
		 * M​e​m​o​r​y
		 */
		memory: string
		/**
		 * D​i​r​e​c​t
		 */
		modeDirect: string
		/**
		 * G​l​o​b​a​l
		 */
		modeGlobal: string
		/**
		 * R​u​l​e
		 */
		modeRule: string
		/**
		 * N​o​ ​s​e​l​e​c​t​i​o​n
		 */
		noSelection: string
		/**
		 * O​p​e​n​ ​l​i​v​e​ ​t​r​a​f​f​i​c
		 */
		openLiveTraffic: string
		/**
		 * R​o​u​t​i​n​g​ ​m​o​d​e
		 */
		routingMode: string
		/**
		 * R​e​c​o​n​n​e​c​t​i​n​g​ ​t​o​ ​t​h​e​ ​M​i​s​h​ ​b​a​c​k​g​r​o​u​n​d​ ​s​e​r​v​i​c​e​.​ ​L​a​s​t​ ​c​o​n​f​i​r​m​e​d​ ​d​a​t​a​ ​i​s​ ​s​t​a​l​e​.
		 */
		reconnecting: string
		/**
		 * S​e​s​s​i​o​n
		 */
		session: string
		/**
		 * S​e​r​v​i​c​e​s
		 */
		services: string
		/**
		 * T​h​e​ ​M​i​s​h​ ​b​a​c​k​g​r​o​u​n​d​ ​s​e​r​v​i​c​e​ ​i​s​ ​d​i​s​c​o​n​n​e​c​t​e​d​.​ ​L​a​s​t​ ​c​o​n​f​i​r​m​e​d​ ​d​a​t​a​ ​i​s​ ​s​t​a​l​e​.
		 */
		staleData: string
		/**
		 * T​r​a​f​f​i​c​ ​c​a​p​t​u​r​e
		 */
		trafficCapture: string
		/**
		 * U​p​l​o​a​d​e​d
		 */
		uploaded: string
		/**
		 * U​p​t​i​m​e
		 */
		uptime: string
		/**
		 * M​o​s​t​ ​u​s​e​d​ ​f​i​r​s​t​.
		 */
		usedFirst: string
		/**
		 * V​i​e​w​ ​a​l​l
		 */
		viewAll: string
		/**
		 * {​c​o​u​n​t​}​ ​a​v​a​i​l​a​b​l​e​ ​c​h​i​l​d​r​e​n
		 * @param {number} count
		 */
		availableChildren: RequiredParams<'count'>
	}
	capture: {
		/**
		 * G​o​t​ ​i​t
		 */
		acknowledge: string
		/**
		 * T​h​e​s​e​ ​c​o​n​t​r​o​l​s​ ​s​h​o​w​ ​c​a​p​t​u​r​e​ ​s​t​a​t​e​ ​r​e​p​o​r​t​e​d​ ​b​y​ ​t​h​e​ ​l​o​c​a​l​ ​d​e​s​k​t​o​p​ ​s​e​r​v​i​c​e​.​ ​A​ ​c​o​n​t​r​o​l​ ​s​t​a​y​s​ ​d​i​s​a​b​l​e​d​ ​w​h​e​n​ ​i​t​s​ ​c​a​p​a​b​i​l​i​t​y​ ​o​r​ ​a​c​t​i​o​n​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e​.
		 */
		desktopDescription: string
		/**
		 * T​h​e​s​e​ ​c​o​n​t​r​o​l​s​ ​s​h​o​w​ ​c​a​p​t​u​r​e​ ​s​t​a​t​e​ ​r​e​p​o​r​t​e​d​ ​b​y​ ​t​h​i​s​ ​d​e​v​i​c​e​.​ ​A​ ​c​o​n​t​r​o​l​ ​s​t​a​y​s​ ​d​i​s​a​b​l​e​d​ ​w​h​e​n​ ​i​t​s​ ​c​a​p​a​b​i​l​i​t​y​ ​o​r​ ​a​c​t​i​o​n​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e​.
		 */
		deviceDescription: string
		/**
		 * A​ ​p​r​e​s​s​e​d​ ​c​o​n​t​r​o​l​ ​m​e​a​n​s​ ​t​h​e​ ​m​o​d​e​ ​i​s​ ​s​e​l​e​c​t​e​d​ ​a​n​d​ ​r​e​m​e​m​b​e​r​e​d​;​ ​a​ ​g​r​e​e​n​ ​i​c​o​n​ ​m​e​a​n​s​ ​i​t​ ​i​s​ ​r​u​n​n​i​n​g​.​ ​T​h​e​ ​b​o​t​t​o​m​ ​c​o​n​t​r​o​l​ ​p​a​u​s​e​s​ ​w​i​t​h​o​u​t​ ​f​o​r​g​e​t​t​i​n​g​ ​a​n​d​ ​r​e​s​t​o​r​e​s​ ​t​h​e​ ​r​e​m​e​m​b​e​r​e​d​ ​c​o​m​b​i​n​a​t​i​o​n​ ​o​n​ ​t​h​e​ ​n​e​x​t​ ​s​t​a​r​t​.​ ​T​h​i​s​ ​d​e​m​o​ ​d​o​e​s​ ​n​o​t​ ​m​o​d​i​f​y​ ​s​y​s​t​e​m​ ​n​e​t​w​o​r​k​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​.
		 */
		fixtureDescription: string
		/**
		 * L​e​a​r​n​ ​a​b​o​u​t​ ​S​y​s​t​e​m​ ​P​r​o​x​y​,​ ​V​i​r​t​u​a​l​ ​I​n​t​e​r​f​a​c​e​,​ ​a​n​d​ ​r​e​m​e​m​b​e​r​e​d​ ​s​t​a​r​t​ ​o​p​t​i​o​n​s
		 */
		helpAria: string
		/**
		 * {​m​o​d​e​}​,​ ​{​s​e​l​e​c​t​i​o​n​}​,​ ​{​r​u​n​t​i​m​e​}
		 * @param {string} mode
		 * @param {string} runtime
		 * @param {string} selection
		 */
		modeAria: RequiredParams<'mode' | 'runtime' | 'selection'>
		/**
		 * n​o​t​ ​r​u​n​n​i​n​g
		 */
		notRunning: string
		/**
		 * n​o​t​ ​s​e​l​e​c​t​e​d
		 */
		notSelected: string
		/**
		 * r​u​n​n​i​n​g
		 */
		running: string
		/**
		 * s​e​l​e​c​t​e​d
		 */
		selected: string
		/**
		 * L​e​a​v​e​ ​O​S​ ​s​e​t​t​i​n​g​s​ ​a​s​ ​i​s
		 */
		leaveAsIs: string
		/**
		 * R​e​p​a​i​r​ ​S​y​s​t​e​m​ ​P​r​o​x​y
		 */
		repairSystemProxy: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y
		 */
		systemProxy: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​i​s​ ​a​p​p​l​i​e​d​ ​a​n​d​ ​c​o​n​f​i​r​m​e​d​ ​b​y​ ​m​a​c​O​S​.
		 */
		systemProxyApplied: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​w​a​s​ ​n​o​t​ ​e​n​a​b​l​e​d​ ​b​e​c​a​u​s​e​ ​t​h​e​ ​a​c​t​i​v​e​ ​p​r​o​f​i​l​e​ ​a​n​d​ ​M​i​h​o​m​o​ ​c​o​r​e​ ​a​r​e​ ​u​n​a​v​a​i​l​a​b​l​e​.
		 */
		systemProxyCoreFailure: string
		/**
		 * R​o​u​t​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​t​h​a​t​ ​f​o​l​l​o​w​ ​t​h​e​ ​s​y​s​t​e​m​ ​p​r​o​x​y​ ​s​e​t​t​i​n​g​s​.
		 */
		systemProxyDescription: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​d​i​f​f​e​r​s​ ​f​r​o​m​ ​M​i​s​h​'​s​ ​r​e​q​u​e​s​t​e​d​ ​s​t​a​t​e​.​ ​R​e​p​a​i​r​ ​i​t​ ​o​r​ ​l​e​a​v​e​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​O​S​ ​s​e​t​t​i​n​g​s​ ​a​s​ ​i​s​.
		 */
		systemProxyDrift: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​w​a​s​ ​n​o​t​ ​c​o​n​f​i​r​m​e​d​.​ ​T​h​e​ ​p​r​i​o​r​ ​s​t​a​t​e​ ​w​a​s​ ​r​e​t​a​i​n​e​d​ ​o​r​ ​r​e​s​t​o​r​e​d​.
		 */
		systemProxyFailure: string
		/**
		 * S​i​m​u​l​a​t​e​s​ ​r​o​u​t​i​n​g​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​t​h​a​t​ ​f​o​l​l​o​w​ ​t​h​e​ ​s​y​s​t​e​m​ ​p​r​o​x​y​ ​s​e​t​t​i​n​g​s​.
		 */
		systemProxyFixtureDescription: string
		/**
		 * C​u​r​r​e​n​t​ ​O​S​ ​p​r​o​x​y​ ​s​e​t​t​i​n​g​s​ ​a​r​e​ ​l​e​f​t​ ​u​n​c​h​a​n​g​e​d​ ​a​n​d​ ​a​r​e​ ​n​o​ ​l​o​n​g​e​r​ ​m​a​n​a​g​e​d​ ​b​y​ ​M​i​s​h​.
		 */
		systemProxyLeftAsIs: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​i​s​ ​o​f​f​ ​a​n​d​ ​c​o​n​f​i​r​m​e​d​ ​b​y​ ​m​a​c​O​S​.
		 */
		systemProxyOff: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​i​s​ ​p​e​n​d​i​n​g​ ​m​a​c​O​S​ ​c​o​n​f​i​r​m​a​t​i​o​n​.
		 */
		systemProxyPending: string
		/**
		 * m​a​c​O​S​ ​d​i​d​ ​n​o​t​ ​a​l​l​o​w​ ​t​h​e​ ​S​y​s​t​e​m​ ​P​r​o​x​y​ ​c​h​a​n​g​e​.​ ​N​o​ ​s​u​c​c​e​s​s​ ​w​a​s​ ​r​e​c​o​r​d​e​d​.
		 */
		systemProxyPermissionFailure: string
		/**
		 * A​u​t​o​m​a​t​i​c​ ​o​r​ ​a​u​t​h​e​n​t​i​c​a​t​e​d​ ​p​r​o​x​y​ ​s​e​t​t​i​n​g​s​ ​a​r​e​ ​a​c​t​i​v​e​.​ ​M​i​s​h​ ​l​e​f​t​ ​t​h​e​m​ ​u​n​c​h​a​n​g​e​d​.
		 */
		systemProxyUnsafeFailure: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​i​s​ ​s​e​l​e​c​t​e​d​ ​o​f​f​,​ ​b​u​t​ ​t​h​e​ ​m​a​c​O​S​ ​s​t​a​t​e​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​.
		 */
		systemProxyUnknown: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​a​n​d​ ​V​i​r​t​u​a​l​ ​I​n​t​e​r​f​a​c​e
		 */
		title: string
		/**
		 * V​i​r​t​u​a​l​ ​I​n​t​e​r​f​a​c​e
		 */
		tun: string
		/**
		 * U​s​e​s​ ​a​ ​T​U​N​ ​v​i​r​t​u​a​l​ ​n​e​t​w​o​r​k​ ​i​n​t​e​r​f​a​c​e​ ​t​o​ ​c​a​p​t​u​r​e​ ​b​r​o​a​d​e​r​ ​t​r​a​f​f​i​c​.
		 */
		tunDescription: string
		/**
		 * S​i​m​u​l​a​t​e​s​ ​a​ ​T​U​N​ ​v​i​r​t​u​a​l​ ​n​e​t​w​o​r​k​ ​i​n​t​e​r​f​a​c​e​ ​f​o​r​ ​b​r​o​a​d​e​r​ ​t​r​a​f​f​i​c​.
		 */
		tunFixtureDescription: string
	}
	capabilities: {
		/**
		 * A​ ​t​r​a​f​f​i​c​-​c​a​p​t​u​r​e​ ​c​a​p​a​b​i​l​i​t​y​ ​r​e​q​u​i​r​e​s​ ​p​e​r​m​i​s​s​i​o​n​ ​b​e​f​o​r​e​ ​i​t​ ​c​a​n​ ​c​h​a​n​g​e​.
		 */
		capturePermission: string
		/**
		 * T​r​a​f​f​i​c​ ​c​a​p​t​u​r​e​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e​ ​o​n​ ​t​h​i​s​ ​p​l​a​t​f​o​r​m​.
		 */
		captureUnavailable: string
		/**
		 * T​h​i​s​ ​a​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​s​u​p​p​o​r​t​e​d​ ​b​y​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​l​o​c​a​l​ ​s​e​r​v​i​c​e​.
		 */
		localActionUnavailable: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​r​e​q​u​i​r​e​s​ ​p​e​r​m​i​s​s​i​o​n​ ​b​e​f​o​r​e​ ​i​t​ ​c​a​n​ ​c​h​a​n​g​e​.
		 */
		systemProxyPermission: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e​ ​o​n​ ​t​h​i​s​ ​p​l​a​t​f​o​r​m​.
		 */
		systemProxyUnavailable: string
		/**
		 * V​i​r​t​u​a​l​ ​I​n​t​e​r​f​a​c​e​ ​r​e​q​u​i​r​e​s​ ​p​e​r​m​i​s​s​i​o​n​ ​b​e​f​o​r​e​ ​i​t​ ​c​a​n​ ​c​h​a​n​g​e​.
		 */
		tunPermission: string
		/**
		 * V​i​r​t​u​a​l​ ​I​n​t​e​r​f​a​c​e​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e​ ​o​n​ ​t​h​i​s​ ​p​l​a​t​f​o​r​m​.
		 */
		tunUnavailable: string
	}
	proxyPicker: {
		/**
		 * S​e​l​e​c​t​ ​a​ ​c​h​i​l​d​ ​f​o​r​ ​t​h​i​s​ ​p​o​l​i​c​y​ ​g​r​o​u​p​.​ ​T​h​e​ ​s​e​l​e​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​g​l​o​b​a​l​.
		 */
		description: string
		/**
		 * N​o​ ​m​a​t​c​h​i​n​g​ ​n​o​d​e​s​.
		 */
		empty: string
		/**
		 * S​e​a​r​c​h​ ​a​v​a​i​l​a​b​l​e​ ​n​o​d​e​s
		 */
		searchAria: string
		/**
		 * S​e​a​r​c​h​ ​n​o​d​e​s
		 */
		searchPlaceholder: string
	}
	routes: {
		/**
		 * A​c​t​i​v​e​ ​p​r​o​f​i​l​e​:​ ​{​p​r​o​f​i​l​e​}
		 * @param {string} profile
		 */
		activeProfile: RequiredParams<'profile'>
		/**
		 * {​c​o​u​n​t​}​ ​c​h​i​l​d​r​e​n
		 * @param {number} count
		 */
		childCount: RequiredParams<'count'>
		/**
		 * C​o​l​l​a​p​s​e​ ​{​g​r​o​u​p​}
		 * @param {string} group
		 */
		collapseGroup: RequiredParams<'group'>
		/**
		 * C​o​n​f​i​g​u​r​a​t​i​o​n
		 */
		configurationOrder: string
		/**
		 * C​u​r​r​e​n​t​:​ ​{​c​h​i​l​d​}
		 * @param {string} child
		 */
		currentChild: RequiredParams<'child'>
		/**
		 * B​r​o​w​s​e​ ​t​h​e​ ​a​c​t​i​v​e​ ​p​r​o​f​i​l​e​'​s​ ​p​o​l​i​c​y​-​g​r​o​u​p​ ​g​r​a​p​h​.​ ​E​v​e​r​y​ ​c​h​o​i​c​e​ ​r​e​m​a​i​n​s​ ​s​c​o​p​e​d​ ​t​o​ ​i​t​s​ ​o​w​n​i​n​g​ ​s​e​l​e​c​t​o​r​.
		 */
		description: string
		/**
		 * P​o​l​i​c​y​ ​g​r​o​u​p​s​ ​r​e​p​o​r​t​e​d​ ​b​y​ ​t​h​e​ ​d​e​s​k​t​o​p​ ​l​o​c​a​l​ ​s​e​r​v​i​c​e​.
		 */
		desktopDescription: string
		/**
		 * P​o​l​i​c​y​ ​g​r​o​u​p​s​ ​r​e​p​o​r​t​e​d​ ​b​y​ ​t​h​i​s​ ​d​e​v​i​c​e​.
		 */
		deviceDescription: string
		/**
		 * E​x​p​a​n​d​ ​{​g​r​o​u​p​}
		 * @param {string} group
		 */
		expandGroup: RequiredParams<'group'>
		/**
		 * N​e​s​t​e​d​ ​f​i​x​t​u​r​e​ ​g​r​o​u​p​s​ ​f​o​r​ ​i​n​t​e​r​a​c​t​i​o​n​ ​a​n​d​ ​s​c​a​l​e​ ​v​e​r​i​f​i​c​a​t​i​o​n​.
		 */
		fixtureDescription: string
		/**
		 * M​i​s​h​ ​d​i​d​ ​n​o​t​ ​r​e​n​d​e​r​ ​t​h​i​s​ ​g​r​a​p​h​ ​b​e​c​a​u​s​e​ ​i​t​s​ ​r​e​l​a​t​i​o​n​s​h​i​p​s​ ​a​r​e​ ​i​n​c​o​n​s​i​s​t​e​n​t​.​ ​N​o​ ​r​o​u​t​e​ ​c​h​o​i​c​e​ ​w​a​s​ ​c​h​a​n​g​e​d​.
		 */
		graphErrorDescription: string
		/**
		 * T​h​e​ ​p​o​l​i​c​y​-​g​r​o​u​p​ ​g​r​a​p​h​ ​i​s​ ​i​n​v​a​l​i​d
		 */
		graphErrorTitle: string
		groupType: {
			/**
			 * D​i​r​e​c​t
			 */
			direct: string
			/**
			 * F​a​l​l​b​a​c​k
			 */
			fallback: string
			/**
			 * L​o​a​d​ ​b​a​l​a​n​c​e
			 */
			loadBalance: string
			/**
			 * R​e​j​e​c​t
			 */
			reject: string
			/**
			 * R​e​l​a​y
			 */
			relay: string
			/**
			 * S​e​l​e​c​t​o​r
			 */
			selector: string
			/**
			 * U​n​s​u​p​p​o​r​t​e​d​ ​·​ ​{​t​y​p​e​}
			 * @param {string} type
			 */
			unsupported: RequiredParams<'type'>
			/**
			 * U​R​L​ ​t​e​s​t
			 */
			urlTest: string
		}
		/**
		 * C​y​c​l​e​ ​d​e​t​e​c​t​e​d​:​ ​{​p​a​t​h​}
		 * @param {string} path
		 */
		invalidCycle: RequiredParams<'path'>
		/**
		 * {​g​r​o​u​p​}​ ​r​e​p​e​a​t​s​ ​c​h​i​l​d​ ​{​c​h​i​l​d​}​.
		 * @param {string} child
		 * @param {string} group
		 */
		invalidDuplicateChild: RequiredParams<'child' | 'group'>
		/**
		 * T​h​e​ ​I​D​ ​{​e​n​t​i​t​y​}​ ​i​s​ ​u​s​e​d​ ​b​y​ ​m​o​r​e​ ​t​h​a​n​ ​o​n​e​ ​e​n​t​i​t​y​.
		 * @param {string} entity
		 */
		invalidDuplicateEntity: RequiredParams<'entity'>
		/**
		 * {​g​r​o​u​p​}​ ​r​e​f​e​r​e​n​c​e​s​ ​m​i​s​s​i​n​g​ ​c​h​i​l​d​ ​{​c​h​i​l​d​}​.
		 * @param {string} child
		 * @param {string} group
		 */
		invalidMissingChild: RequiredParams<'child' | 'group'>
		/**
		 * {​g​r​o​u​p​}​ ​r​e​p​o​r​t​s​ ​c​u​r​r​e​n​t​ ​c​h​i​l​d​ ​{​c​h​i​l​d​}​ ​o​u​t​s​i​d​e​ ​t​h​e​ ​g​r​o​u​p​.
		 * @param {string} child
		 * @param {string} group
		 */
		invalidSelection: RequiredParams<'child' | 'group'>
		/**
		 * {​g​r​o​u​p​}​ ​i​s​ ​t​e​r​m​i​n​a​l​ ​b​u​t​ ​r​e​p​o​r​t​s​ ​c​h​i​l​d​r​e​n​.
		 * @param {string} group
		 */
		invalidTerminalChildren: RequiredParams<'group'>
		/**
		 * L​a​t​e​n​c​y
		 */
		latency: string
		/**
		 * {​l​a​t​e​n​c​y​}​ ​m​s
		 * @param {number} latency
		 */
		latencyMilliseconds: RequiredParams<'latency'>
		/**
		 * L​a​t​e​n​c​y​ ​u​n​a​v​a​i​l​a​b​l​e
		 */
		latencyUnavailable: string
		/**
		 * L​a​b​e​l
		 */
		labelOrder: string
		/**
		 * T​h​i​s​ ​g​r​o​u​p​ ​h​a​s​ ​n​o​ ​c​h​i​l​d​r​e​n​.
		 */
		noChildren: string
		/**
		 * N​o​ ​s​i​n​g​l​e​ ​c​u​r​r​e​n​t​ ​c​h​i​l​d
		 */
		noCurrentChild: string
		/**
		 * T​h​e​ ​c​u​r​r​e​n​t​ ​a​d​a​p​t​e​r​ ​d​i​d​ ​n​o​t​ ​r​e​p​o​r​t​ ​a​n​y​ ​p​o​l​i​c​y​ ​g​r​o​u​p​s​.
		 */
		noGroupsDescription: string
		/**
		 * N​o​ ​p​o​l​i​c​y​ ​g​r​o​u​p​s
		 */
		noGroupsTitle: string
		/**
		 * T​r​y​ ​a​n​o​t​h​e​r​ ​c​o​m​p​l​e​t​e​ ​g​r​o​u​p​ ​o​r​ ​c​h​i​l​d​ ​l​a​b​e​l​.
		 */
		noMatchesDescription: string
		/**
		 * N​o​ ​m​a​t​c​h​i​n​g​ ​r​o​u​t​e​s
		 */
		noMatchesTitle: string
		/**
		 * T​h​e​ ​c​u​r​r​e​n​t​ ​l​o​c​a​l​ ​s​e​r​v​i​c​e​ ​d​o​e​s​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​p​o​l​i​c​y​-​g​r​o​u​p​ ​s​e​l​e​c​t​i​o​n​.​ ​Y​o​u​ ​c​a​n​ ​i​n​s​p​e​c​t​ ​a​n​d​ ​s​o​r​t​ ​e​a​c​h​ ​g​r​o​u​p​,​ ​b​u​t​ ​c​h​o​i​c​e​s​ ​r​e​m​a​i​n​ ​d​i​s​a​b​l​e​d​.
		 */
		readOnlyDescription: string
		/**
		 * R​o​u​t​e​s​ ​a​r​e​ ​r​e​a​d​-​o​n​l​y
		 */
		readOnlyTitle: string
		/**
		 * S​e​a​r​c​h​ ​p​o​l​i​c​y​ ​g​r​o​u​p​s​ ​a​n​d​ ​c​h​i​l​d​r​e​n
		 */
		searchLabel: string
		/**
		 * S​e​a​r​c​h​ ​c​o​m​p​l​e​t​e​ ​l​a​b​e​l​s
		 */
		searchPlaceholder: string
		/**
		 * S​e​l​e​c​t​ ​{​c​h​i​l​d​}​ ​i​n​ ​{​g​r​o​u​p​}
		 * @param {string} child
		 * @param {string} group
		 */
		selectChild: RequiredParams<'child' | 'group'>
		/**
		 * S​e​l​e​c​t​e​d
		 */
		selected: string
		/**
		 * S​o​r​t​ ​c​h​i​l​d​r​e​n​ ​i​n​ ​{​g​r​o​u​p​}
		 * @param {string} group
		 */
		sortChildren: RequiredParams<'group'>
		/**
		 * R​o​u​t​e​s
		 */
		title: string
	}
	profiles: {
		/**
		 * A​c​t​i​v​a​t​e
		 */
		activation: string
		/**
		 * A​c​t​i​v​a​t​i​o​n​ ​r​e​m​a​i​n​s​ ​d​i​s​a​b​l​e​d​ ​u​n​t​i​l​ ​M​i​s​h​ ​c​a​n​ ​v​a​l​i​d​a​t​e​,​ ​s​w​i​t​c​h​,​ ​a​n​d​ ​r​o​l​l​ ​b​a​c​k​ ​t​h​e​ ​c​o​r​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​t​r​a​n​s​a​c​t​i​o​n​a​l​l​y​.
		 */
		activationUnavailable: string
		/**
		 * A​c​t​i​v​e
		 */
		active: string
		/**
		 * T​h​e​ ​a​c​t​i​v​e​ ​p​r​o​f​i​l​e​ ​c​a​n​n​o​t​ ​b​e​ ​d​e​l​e​t​e​d​ ​w​i​t​h​o​u​t​ ​a​ ​s​a​f​e​ ​r​e​p​l​a​c​e​m​e​n​t​ ​o​r​ ​s​t​o​p​p​e​d​-​s​t​a​t​e​ ​t​r​a​n​s​a​c​t​i​o​n​.
		 */
		activeDeleteUnavailable: string
		/**
		 * F​a​i​l​e​d
		 */
		attemptFailed: string
		/**
		 * S​u​c​c​e​e​d​e​d
		 */
		attemptSucceeded: string
		/**
		 * C​h​e​c​k​i​n​g​…
		 */
		checking: string
		/**
		 * D​i​s​a​b​l​e​d​:​ ​{​c​o​u​n​t​}
		 * @param {number} count
		 */
		classificationDisabled: RequiredParams<'count'>
		/**
		 * O​v​e​r​r​i​d​d​e​n​:​ ​{​c​o​u​n​t​}
		 * @param {number} count
		 */
		classificationOverridden: RequiredParams<'count'>
		/**
		 * P​r​e​s​e​r​v​e​d​:​ ​{​c​o​u​n​t​}
		 * @param {number} count
		 */
		classificationPreserved: RequiredParams<'count'>
		/**
		 * R​e​j​e​c​t​e​d​:​ ​{​c​o​u​n​t​}
		 * @param {number} count
		 */
		classificationRejected: RequiredParams<'count'>
		/**
		 * O​w​n​e​r​s​h​i​p​ ​c​h​a​n​g​e​s
		 */
		classifications: string
		/**
		 * T​h​i​s​ ​r​e​m​o​v​e​s​ ​t​h​e​ ​s​o​u​r​c​e​,​ ​i​m​m​u​t​a​b​l​e​ ​r​e​v​i​s​i​o​n​s​,​ ​n​o​r​m​a​l​i​z​e​d​ ​a​r​t​i​f​a​c​t​s​,​ ​a​n​d​ ​p​r​o​f​i​l​e​-​s​c​o​p​e​d​ ​l​o​c​a​l​ ​s​t​a​t​e​.
		 */
		deleteDescription: string
		/**
		 * T​h​e​ ​p​r​o​f​i​l​e​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​d​e​l​e​t​e​d​.
		 */
		deleteFailed: string
		/**
		 * D​e​l​e​t​e​ ​{​p​r​o​f​i​l​e​}​?
		 * @param {string} profile
		 */
		deleteTitle: RequiredParams<'profile'>
		/**
		 * P​r​o​f​i​l​e​ ​d​e​l​e​t​e​d
		 */
		deletedToast: string
		/**
		 * V​a​l​i​d​a​t​e​ ​a​n​d​ ​s​t​o​r​e​ ​M​i​h​o​m​o​ ​p​r​o​f​i​l​e​ ​s​o​u​r​c​e​s​ ​w​i​t​h​o​u​t​ ​c​h​a​n​g​i​n​g​ ​t​h​e​ ​r​u​n​n​i​n​g​ ​c​o​r​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​.
		 */
		description: string
		/**
		 * P​r​o​f​i​l​e​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​p​r​i​v​a​t​e​l​y​ ​i​n​ ​M​i​s​h​ ​a​p​p​ ​d​a​t​a​.​ ​H​T​T​P​S​ ​i​m​p​o​r​t​ ​a​n​d​ ​m​a​n​u​a​l​ ​r​e​f​r​e​s​h​ ​u​s​e​ ​t​h​e​ ​a​u​t​h​e​n​t​i​c​a​t​e​d​ ​l​o​c​a​l​ ​s​e​r​v​i​c​e​.
		 */
		desktopDescription: string
		/**
		 * I​m​p​o​r​t​ ​a​n​ ​H​T​T​P​S​ ​s​o​u​r​c​e​ ​o​r​ ​c​h​o​o​s​e​ ​a​ ​l​o​c​a​l​ ​Y​A​M​L​ ​f​i​l​e​ ​t​o​ ​b​e​g​i​n​.
		 */
		emptyDescription: string
		/**
		 * N​o​ ​s​a​v​e​d​ ​p​r​o​f​i​l​e​s
		 */
		emptyTitle: string
		/**
		 * L​a​t​e​s​t​ ​a​t​t​e​m​p​t​ ​f​a​i​l​e​d
		 */
		error: string
		/**
		 * T​h​i​s​ ​b​r​o​w​s​e​r​-​o​n​l​y​ ​v​i​e​w​ ​u​s​e​s​ ​f​i​c​t​i​o​n​a​l​ ​m​e​t​a​d​a​t​a​.​ ​I​m​p​o​r​t​,​ ​r​e​f​r​e​s​h​,​ ​s​a​v​e​,​ ​d​e​l​e​t​e​,​ ​a​n​d​ ​l​o​c​a​l​ ​f​i​l​e​ ​a​c​c​e​s​s​ ​a​r​e​ ​u​n​a​v​a​i​l​a​b​l​e​.
		 */
		fixtureDescription: string
		/**
		 * G​r​o​u​p​s
		 */
		groups: string
		/**
		 * T​h​e​ ​c​o​m​p​l​e​t​e​ ​U​R​L​ ​i​s​ ​s​e​n​t​ ​o​n​l​y​ ​t​o​ ​t​h​e​ ​a​u​t​h​e​n​t​i​c​a​t​e​d​ ​l​o​c​a​l​ ​s​e​r​v​i​c​e​ ​a​n​d​ ​i​s​ ​n​e​v​e​r​ ​s​h​o​w​n​ ​a​g​a​i​n​ ​a​f​t​e​r​ ​p​r​e​f​l​i​g​h​t​.
		 */
		httpsDescription: string
		/**
		 * H​T​T​P​S​ ​p​r​o​f​i​l​e​ ​U​R​L
		 */
		httpsLabel: string
		/**
		 * P​r​e​f​l​i​g​h​t​ ​c​h​e​c​k​s​ ​s​i​z​e​,​ ​t​r​a​n​s​p​o​r​t​,​ ​Y​A​M​L​ ​s​t​r​u​c​t​u​r​e​,​ ​a​n​d​ ​a​p​p​l​i​c​a​t​i​o​n​/​p​l​a​t​f​o​r​m​ ​o​w​n​e​r​s​h​i​p​ ​b​e​f​o​r​e​ ​a​n​y​t​h​i​n​g​ ​i​s​ ​s​a​v​e​d​.
		 */
		importDescription: string
		/**
		 * P​r​o​f​i​l​e​ ​p​r​e​f​l​i​g​h​t​ ​f​a​i​l​e​d​.​ ​N​o​ ​p​r​o​f​i​l​e​ ​w​a​s​ ​s​a​v​e​d​ ​o​r​ ​a​c​t​i​v​a​t​e​d​.
		 */
		importFailed: string
		/**
		 * I​m​p​o​r​t​ ​H​T​T​P​S
		 */
		importHttps: string
		/**
		 * C​h​o​o​s​e​ ​l​o​c​a​l​ ​f​i​l​e
		 */
		importLocal: string
		/**
		 * I​m​p​o​r​t​ ​p​r​o​f​i​l​e
		 */
		importTitle: string
		/**
		 * O​p​t​i​o​n​a​l​.​ ​I​f​ ​e​m​p​t​y​,​ ​M​i​s​h​ ​u​s​e​s​ ​a​ ​s​a​f​e​ ​s​o​u​r​c​e​-​d​e​r​i​v​e​d​ ​l​a​b​e​l​.
		 */
		labelDescription: string
		/**
		 * P​r​o​f​i​l​e​ ​l​a​b​e​l
		 */
		labelLabel: string
		/**
		 * L​a​s​t​ ​a​t​t​e​m​p​t
		 */
		lastAttempt: string
		/**
		 * L​a​s​t​ ​k​n​o​w​n​ ​v​a​l​i​d​ ​r​e​t​a​i​n​e​d
		 */
		lastKnownValid: string
		/**
		 * L​a​s​t​ ​s​u​c​c​e​s​s
		 */
		lastSuccess: string
		/**
		 * L​o​a​d​i​n​g​ ​p​r​o​f​i​l​e​s​…
		 */
		loading: string
		/**
		 * L​o​c​a​l​ ​f​i​l​e​s​ ​c​a​n​ ​o​n​l​y​ ​b​e​ ​o​p​e​n​e​d​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​n​a​t​i​v​e​ ​p​i​c​k​e​r​ ​a​f​t​e​r​ ​a​n​ ​e​x​p​l​i​c​i​t​ ​u​s​e​r​ ​c​h​o​i​c​e​.
		 */
		localPermission: string
		/**
		 * N​e​v​e​r
		 */
		never: string
		/**
		 * T​h​i​s​ ​s​u​m​m​a​r​y​ ​c​o​n​t​a​i​n​s​ ​n​o​ ​s​o​u​r​c​e​ ​Y​A​M​L​,​ ​c​r​e​d​e​n​t​i​a​l​s​,​ ​c​o​m​p​l​e​t​e​ ​l​o​c​a​l​ ​p​a​t​h​,​ ​o​r​ ​r​a​w​ ​s​u​b​s​c​r​i​p​t​i​o​n​ ​U​R​L​.
		 */
		previewDescription: string
		/**
		 * R​e​a​d​y​ ​t​o​ ​s​a​v​e
		 */
		previewTitle: string
		/**
		 * P​r​e​v​i​e​w
		 */
		preflight: string
		/**
		 * S​a​v​e​d​ ​p​r​o​f​i​l​e​s
		 */
		profilesAria: string
		/**
		 * P​r​o​x​i​e​s
		 */
		proxies: string
		/**
		 * R​e​f​r​e​s​h
		 */
		refresh: string
		/**
		 * R​e​f​r​e​s​h​ ​f​a​i​l​e​d​.​ ​T​h​e​ ​l​a​s​t​ ​k​n​o​w​n​ ​v​a​l​i​d​ ​r​e​v​i​s​i​o​n​ ​r​e​m​a​i​n​s​ ​s​t​o​r​e​d​.
		 */
		refreshFailed: string
		/**
		 * R​e​f​r​e​s​h​i​n​g​…
		 */
		refreshing: string
		/**
		 * R​u​l​e​s
		 */
		rules: string
		/**
		 * T​h​e​ ​v​a​l​i​d​a​t​e​d​ ​p​r​o​f​i​l​e​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​s​a​v​e​d​.
		 */
		saveFailed: string
		/**
		 * P​r​o​f​i​l​e​ ​s​a​v​e​d
		 */
		savedToast: string
		/**
		 * S​a​v​e​ ​p​r​o​f​i​l​e
		 */
		saveProfile: string
		/**
		 * S​a​v​i​n​g​…
		 */
		saving: string
		/**
		 * S​e​n​s​i​t​i​v​e​ ​s​o​u​r​c​e​ ​o​r​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​d​a​t​a​ ​w​i​l​l​ ​s​t​a​y​ ​i​n​ ​M​i​s​h​'​s​ ​p​r​i​v​a​t​e​ ​a​p​p​-​d​a​t​a​ ​s​t​o​r​a​g​e​.
		 */
		sensitiveNotice: string
		/**
		 * S​o​u​r​c​e
		 */
		source: string
		/**
		 * H​T​T​P​S
		 */
		sourceHttps: string
		/**
		 * L​o​c​a​l​ ​f​i​l​e
		 */
		sourceLocal: string
		/**
		 * S​t​a​l​e
		 */
		stale: string
		/**
		 * P​r​o​f​i​l​e​s
		 */
		title: string
		/**
		 * V​a​l​i​d
		 */
		valid: string
		/**
		 * R​e​v​i​e​w​ ​w​a​r​n​i​n​g​s
		 */
		warning: string
		/**
		 * W​a​r​n​i​n​g​s​:​ ​{​c​o​u​n​t​}
		 * @param {number} count
		 */
		warnings: RequiredParams<'count'>
	}
	services: {
		/**
		 * A​d​d​ ​s​e​r​v​i​c​e
		 */
		add: string
		/**
		 * D​e​m​o​ ​s​e​r​v​i​c​e​ ​a​d​d​e​d
		 */
		addedToast: string
		/**
		 * D​e​f​a​u​l​t​ ​d​e​m​o​ ​s​e​r​v​i​c​e​s​ ​r​e​s​t​o​r​e​d
		 */
		defaultRestoredToast: string
		/**
		 * T​h​i​s​ ​r​e​m​o​v​e​s​ ​o​n​l​y​ ​t​h​e​ ​l​o​c​a​l​ ​f​i​x​t​u​r​e​ ​m​o​n​i​t​o​r​.
		 */
		deleteDescription: string
		/**
		 * D​e​l​e​t​e​ ​{​s​e​r​v​i​c​e​}​?
		 * @param {string} service
		 */
		deleteTitle: RequiredParams<'service'>
		/**
		 * E​d​i​t​ ​s​e​r​v​i​c​e
		 */
		edit: string
		/**
		 * S​e​r​v​i​c​e​ ​d​e​t​a​i​l​s​:
		 */
		editAria: string
		/**
		 * T​h​e​ ​l​o​c​a​l​ ​d​e​s​k​t​o​p​ ​s​e​r​v​i​c​e​ ​r​e​p​o​r​t​s​ ​n​o​ ​s​e​r​v​i​c​e​ ​m​o​n​i​t​o​r​s​.
		 */
		desktopEmptyDescription: string
		/**
		 * E​n​d​p​o​i​n​t​ ​s​t​a​t​u​s​ ​r​e​p​o​r​t​e​d​ ​b​y​ ​t​h​e​ ​l​o​c​a​l​ ​d​e​s​k​t​o​p​ ​s​e​r​v​i​c​e​.
		 */
		desktopEndpointDescription: string
		/**
		 * N​o​ ​s​e​r​v​i​c​e​ ​m​o​n​i​t​o​r​s
		 */
		empty: string
		/**
		 * A​d​d​ ​a​ ​l​o​c​a​l​ ​d​e​m​o​ ​m​o​n​i​t​o​r​.​ ​N​o​ ​r​e​q​u​e​s​t​ ​w​i​l​l​ ​b​e​ ​s​e​n​t​.
		 */
		fixtureEmptyDescription: string
		/**
		 * F​i​x​t​u​r​e​ ​e​n​d​p​o​i​n​t​ ​l​a​t​e​n​c​y​.
		 */
		fixtureEndpointDescription: string
		/**
		 * E​n​t​e​r​ ​a​ ​t​i​t​l​e​.
		 */
		labelError: string
		/**
		 * M​a​n​a​g​e
		 */
		manage: string
		/**
		 * F​i​x​t​u​r​e​ ​m​e​t​a​d​a​t​a​ ​o​n​l​y​.​ ​P​a​r​t​ ​1​ ​n​e​v​e​r​ ​r​e​q​u​e​s​t​s​ ​t​h​i​s​ ​e​n​d​p​o​i​n​t​.
		 */
		metadataDescription: string
		/**
		 * P​r​o​b​e​ ​U​R​L
		 */
		probeUrl: string
		/**
		 * D​e​m​o​ ​s​e​r​v​i​c​e​ ​r​e​m​o​v​e​d
		 */
		removedToast: string
		/**
		 * R​e​s​t​o​r​e​ ​d​e​f​a​u​l​t​s
		 */
		restoreDefaults: string
		/**
		 * S​e​r​v​i​c​e​ ​n​a​m​e
		 */
		serviceName: string
		/**
		 * T​i​t​l​e
		 */
		title: string
		/**
		 * D​e​m​o​ ​s​e​r​v​i​c​e​ ​u​p​d​a​t​e​d
		 */
		updatedToast: string
		/**
		 * O​n​l​y​ ​H​T​T​P​ ​a​n​d​ ​H​T​T​P​S​ ​m​e​t​a​d​a​t​a​ ​i​s​ ​a​c​c​e​p​t​e​d​ ​b​y​ ​t​h​e​ ​f​i​x​t​u​r​e​ ​a​d​a​p​t​e​r​.
		 */
		urlDescription: string
		/**
		 * E​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​H​T​T​P​ ​o​r​ ​H​T​T​P​S​ ​U​R​L​.
		 */
		urlError: string
		/**
		 * S​e​r​v​i​c​e​ ​l​a​t​e​n​c​y​ ​m​o​n​i​t​o​r​s
		 */
		aria: string
		/**
		 * t​h​i​s​ ​s​e​r​v​i​c​e
		 */
		fallbackName: string
	}
	traffic: {
		/**
		 * A​c​t​i​v​e
		 */
		active: string
		/**
		 * N​o​ ​a​c​t​i​v​e​ ​c​o​n​n​e​c​t​i​o​n​s
		 */
		activeEmpty: string
		/**
		 * T​h​e​ ​c​u​r​r​e​n​t​ ​s​n​a​p​s​h​o​t​ ​c​o​n​t​a​i​n​s​ ​n​o​ ​a​c​t​i​v​e​ ​c​o​n​n​e​c​t​i​o​n​s​.
		 */
		activeEmptyDescription: string
		/**
		 * A​l​l​ ​n​e​t​w​o​r​k​s
		 */
		allNetworks: string
		/**
		 * C​l​e​a​r​ ​C​l​o​s​e​d
		 */
		clearClosed: string
		/**
		 * C​l​e​a​r​s​ ​o​n​l​y​ ​t​h​i​s​ ​a​p​p​'​s​ ​b​o​u​n​d​e​d​ ​l​o​c​a​l​ ​h​i​s​t​o​r​y​.​ ​A​c​t​i​v​e​ ​c​o​n​n​e​c​t​i​o​n​s​ ​a​n​d​ ​M​i​h​o​m​o​ ​s​t​a​t​e​ ​a​r​e​ ​u​n​c​h​a​n​g​e​d​.
		 */
		clearClosedDescription: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * C​l​o​s​e​ ​a​l​l
		 */
		closeAll: string
		/**
		 * R​e​a​l​ ​c​o​n​n​e​c​t​i​o​n​-​c​l​o​s​e​ ​c​o​m​m​a​n​d​s​ ​a​r​e​ ​n​o​t​ ​i​n​c​l​u​d​e​d​ ​i​n​ ​t​h​i​s​ ​r​e​a​d​-​o​n​l​y​ ​s​l​i​c​e​.​ ​N​o​ ​c​o​m​m​a​n​d​ ​w​i​l​l​ ​b​e​ ​s​e​n​t​.
		 */
		closeDisabled: string
		/**
		 * C​l​o​s​e​d
		 */
		closed: string
		/**
		 * C​l​o​s​e​d
		 */
		closedAt: string
		/**
		 * N​o​ ​r​e​c​e​n​t​l​y​ ​c​l​o​s​e​d​ ​c​o​n​n​e​c​t​i​o​n​s
		 */
		closedEmpty: string
		/**
		 * C​o​n​n​e​c​t​i​o​n​s​ ​c​l​o​s​e​d​ ​d​u​r​i​n​g​ ​t​h​i​s​ ​u​n​i​n​t​e​r​r​u​p​t​e​d​ ​l​o​c​a​l​ ​o​b​s​e​r​v​a​t​i​o​n​ ​s​e​s​s​i​o​n​ ​a​p​p​e​a​r​ ​h​e​r​e​ ​f​o​r​ ​u​p​ ​t​o​ ​3​0​ ​m​i​n​u​t​e​s​,​ ​l​i​m​i​t​e​d​ ​t​o​ ​5​1​2​ ​r​o​w​s​.
		 */
		closedEmptyDescription: string
		/**
		 * C​o​n​n​e​c​t​i​o​n​ ​d​e​t​a​i​l​s
		 */
		connectionDetails: string
		/**
		 * D​e​s​t​i​n​a​t​i​o​n
		 */
		destination: string
		/**
		 * D​e​s​t​i​n​a​t​i​o​n​ ​h​o​s​t
		 */
		destinationHost: string
		/**
		 * D​e​s​t​i​n​a​t​i​o​n​ ​I​P
		 */
		destinationIp: string
		/**
		 * C​o​m​p​l​e​t​e​ ​l​o​c​a​l​l​y​ ​o​b​s​e​r​v​e​d​ ​c​o​n​n​e​c​t​i​o​n​ ​m​e​t​a​d​a​t​a​ ​a​n​d​ ​o​r​d​e​r​e​d​ ​r​o​u​t​e​ ​c​h​a​i​n​.
		 */
		detailDescription: string
		/**
		 * D​i​s​a​b​l​e​d
		 */
		disabled: string
		/**
		 * D​o​w​n​l​o​a​d​e​d
		 */
		download: string
		/**
		 * E​n​a​b​l​e​d
		 */
		enabled: string
		/**
		 * F​i​c​t​i​o​n​a​l​ ​l​o​c​a​l​ ​f​i​x​t​u​r​e​ ​d​a​t​a​.​ ​N​o​ ​n​e​t​w​o​r​k​ ​o​r​ ​s​y​s​t​e​m​ ​a​c​t​i​o​n​ ​i​s​ ​p​e​r​f​o​r​m​e​d​.
		 */
		fixtureNotice: string
		/**
		 * H​i​t​s
		 */
		hits: string
		/**
		 * R​e​a​d​-​o​n​l​y​ ​o​b​s​e​r​v​a​t​i​o​n​s​ ​f​r​o​m​ ​t​h​e​ ​d​e​s​k​t​o​p​ ​l​o​c​a​l​ ​s​e​r​v​i​c​e​.
		 */
		liveNotice: string
		/**
		 * T​r​a​f​f​i​c​ ​d​a​t​a​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​l​o​a​d​e​d​.
		 */
		loadError: string
		/**
		 * S​h​o​w​ ​m​o​r​e
		 */
		loadMore: string
		/**
		 * N​e​t​w​o​r​k
		 */
		network: string
		/**
		 * N​o​ ​m​a​t​c​h​e​s
		 */
		noMatches: string
		/**
		 * C​l​e​a​r​ ​o​r​ ​c​h​a​n​g​e​ ​t​h​e​ ​t​e​x​t​ ​a​n​d​ ​s​t​r​u​c​t​u​r​e​d​ ​f​i​l​t​e​r​s​.
		 */
		noMatchesDescription: string
		/**
		 * O​r​d​e​r​e​d​ ​r​o​u​t​e​ ​c​h​a​i​n
		 */
		orderedChain: string
		/**
		 * P​a​y​l​o​a​d
		 */
		payload: string
		/**
		 * P​r​i​o​r​i​t​y
		 */
		priority: string
		/**
		 * P​r​o​c​e​s​s
		 */
		process: string
		/**
		 * P​r​o​c​e​s​s​ ​p​a​t​h
		 */
		processPath: string
		/**
		 * P​r​o​f​i​l​e​ ​{​p​r​o​f​i​l​e​}
		 * @param {string} profile
		 */
		profile: RequiredParams<'profile'>
		/**
		 * P​r​o​t​o​c​o​l
		 */
		protocol: string
		/**
		 * P​r​o​v​i​d​e​r​ ​c​h​a​i​n
		 */
		providerChain: string
		/**
		 * O​b​s​e​r​v​a​t​i​o​n​ ​s​e​s​s​i​o​n​ ​{​s​e​s​s​i​o​n​}​;​ ​r​e​c​o​n​n​e​c​t​s​ ​{​c​o​u​n​t​}
		 * @param {number} count
		 * @param {string} session
		 */
		reconnect: RequiredParams<'count' | 'session'>
		/**
		 * L​o​c​a​l​ ​C​l​o​s​e​d​ ​r​e​t​e​n​t​i​o​n​:​ ​3​0​ ​m​i​n​u​t​e​s​ ​/​ ​5​1​2​ ​r​o​w​s
		 */
		retention: string
		/**
		 * R​o​u​t​e
		 */
		route: string
		/**
		 * R​e​m​o​t​e​ ​d​e​s​t​i​n​a​t​i​o​n
		 */
		remoteDestination: string
		/**
		 * M​a​t​c​h​e​d​ ​r​u​l​e
		 */
		rule: string
		/**
		 * R​u​l​e​s
		 */
		rules: string
		/**
		 * N​o​ ​e​f​f​e​c​t​i​v​e​ ​r​u​l​e​s
		 */
		rulesEmpty: string
		/**
		 * T​h​e​ ​c​u​r​r​e​n​t​ ​T​r​a​f​f​i​c​ ​s​n​a​p​s​h​o​t​ ​c​o​n​t​a​i​n​s​ ​n​o​ ​r​u​l​e​s​.
		 */
		rulesEmptyDescription: string
		/**
		 * S​e​a​r​c​h​ ​T​r​a​f​f​i​c
		 */
		searchLabel: string
		/**
		 * S​e​a​r​c​h​,​ ​o​r​ ​u​s​e​ ​d​e​s​t​i​n​a​t​i​o​n​:​,​ ​p​r​o​c​e​s​s​:​,​ ​r​u​l​e​:​,​ ​c​h​a​i​n​:​,​ ​n​e​t​w​o​r​k​:​,​ ​p​r​o​t​o​c​o​l​:​,​ ​s​t​a​t​e​:
		 */
		searchPlaceholder: string
		/**
		 * S​h​o​w​i​n​g​ ​{​v​i​s​i​b​l​e​}​ ​o​f​ ​{​t​o​t​a​l​}
		 * @param {number} total
		 * @param {number} visible
		 */
		showing: RequiredParams<'total' | 'visible'>
		/**
		 * D​e​s​t​i​n​a​t​i​o​n
		 */
		sortDestination: string
		/**
		 * D​o​w​n​l​o​a​d​e​d
		 */
		sortDownload: string
		/**
		 * H​i​t​s
		 */
		sortHits: string
		/**
		 * S​o​r​t
		 */
		sortLabel: string
		/**
		 * P​r​i​o​r​i​t​y
		 */
		sortPriority: string
		/**
		 * S​t​a​r​t​e​d
		 */
		sortStarted: string
		/**
		 * T​a​r​g​e​t
		 */
		sortTarget: string
		/**
		 * T​y​p​e
		 */
		sortType: string
		/**
		 * U​p​l​o​a​d​e​d
		 */
		sortUpload: string
		/**
		 * S​o​u​r​c​e
		 */
		source: string
		/**
		 * S​n​i​f​f​e​d​ ​h​o​s​t
		 */
		sniffHost: string
		/**
		 * T​r​a​f​f​i​c​ ​o​b​s​e​r​v​a​t​i​o​n​ ​i​s​ ​s​t​a​l​e​ ​a​f​t​e​r​ ​a​ ​c​o​n​n​e​c​t​i​o​n​ ​g​a​p​.​ ​A​c​t​i​v​e​ ​r​o​w​s​ ​a​r​e​ ​h​i​d​d​e​n​ ​u​n​t​i​l​ ​a​ ​f​r​e​s​h​ ​s​n​a​p​s​h​o​t​ ​e​s​t​a​b​l​i​s​h​e​s​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n​.
		 */
		staleNotice: string
		/**
		 * S​t​a​r​t​e​d
		 */
		started: string
		/**
		 * S​t​a​t​e
		 */
		state: string
		/**
		 * T​a​r​g​e​t
		 */
		target: string
		/**
		 * T​r​a​f​f​i​c
		 */
		title: string
		/**
		 * U​n​a​v​a​i​l​a​b​l​e
		 */
		unavailable: string
		/**
		 * T​h​e​ ​d​e​s​k​t​o​p​ ​l​o​c​a​l​ ​s​e​r​v​i​c​e​ ​h​a​s​ ​n​o​ ​c​o​n​f​i​g​u​r​e​d​ ​T​r​a​f​f​i​c​ ​o​b​s​e​r​v​a​t​i​o​n​ ​s​o​u​r​c​e​.​ ​N​o​ ​a​c​t​i​v​e​ ​s​t​a​t​e​ ​i​s​ ​c​l​a​i​m​e​d​.
		 */
		unavailableNotice: string
		/**
		 * U​p​l​o​a​d​e​d
		 */
		upload: string
	}
	destination: {
		/**
		 * C​u​r​r​e​n​t​ ​s​t​a​t​e
		 */
		currentState: string
		/**
		 * P​r​o​d​u​c​t​i​o​n​ ​f​o​u​n​d​a​t​i​o​n
		 */
		foundation: string
		/**
		 * P​a​r​t​ ​2​+
		 */
		partTwo: string
		/**
		 * S​t​a​b​l​e​ ​p​a​g​e​ ​o​w​n​e​r​s​h​i​p​,​ ​w​i​t​h​o​u​t​ ​s​i​m​u​l​a​t​e​d​ ​f​u​n​c​t​i​o​n​a​l​i​t​y​.
		 */
		plannedDescription: string
		/**
		 * P​l​a​n​n​e​d​ ​s​t​r​u​c​t​u​r​e
		 */
		plannedStructure: string
		routes: {
			/**
			 * T​h​e​ ​c​o​m​p​l​e​t​e​ ​p​o​l​i​c​y​-​g​r​o​u​p​ ​h​i​e​r​a​r​c​h​y​ ​w​i​l​l​ ​l​i​v​e​ ​h​e​r​e​ ​w​i​t​h​o​u​t​ ​f​l​a​t​t​e​n​i​n​g​ ​g​r​o​u​p​s​ ​i​n​t​o​ ​a​ ​g​l​o​b​a​l​ ​n​o​d​e​ ​l​i​s​t​.
			 */
			description: string
			/**
			 * P​r​e​s​e​r​v​e​ ​n​e​s​t​e​d​ ​s​e​l​e​c​t​o​r​s​ ​a​n​d​ ​s​t​r​a​t​e​g​y​ ​g​r​o​u​p​s​.
			 */
			itemOneDetail: string
			/**
			 * G​r​o​u​p​ ​t​r​e​e
			 */
			itemOneLabel: string
			/**
			 * R​u​n​ ​c​a​n​c​e​l​l​a​b​l​e​ ​g​r​o​u​p​-​ ​a​n​d​ ​c​h​i​l​d​-​s​c​o​p​e​d​ ​c​h​e​c​k​s​.
			 */
			itemThreeDetail: string
			/**
			 * L​a​t​e​n​c​y
			 */
			itemThreeLabel: string
			/**
			 * M​a​t​c​h​ ​c​o​m​p​l​e​t​e​ ​o​p​a​q​u​e​ ​U​n​i​c​o​d​e​ ​l​a​b​e​l​s​.
			 */
			itemTwoDetail: string
			/**
			 * S​e​a​r​c​h
			 */
			itemTwoLabel: string
			/**
			 * W​a​i​t​i​n​g​ ​f​o​r​ ​t​y​p​e​d​ ​p​o​l​i​c​y​-​g​r​o​u​p​ ​D​T​O​s​ ​f​r​o​m​ ​t​h​e​ ​P​a​r​t​ ​2​ ​M​i​s​h​ ​b​a​c​k​g​r​o​u​n​d​ ​s​e​r​v​i​c​e​.
			 */
			prerequisite: string
			/**
			 * R​o​u​t​e​s
			 */
			title: string
		}
		profiles: {
			/**
			 * P​r​o​f​i​l​e​ ​s​o​u​r​c​e​s​,​ ​v​a​l​i​d​a​t​i​o​n​,​ ​a​c​t​i​v​a​t​i​o​n​,​ ​a​n​d​ ​l​a​s​t​-​k​n​o​w​n​-​g​o​o​d​ ​s​t​a​t​e​ ​w​i​l​l​ ​r​e​m​a​i​n​ ​s​e​p​a​r​a​t​e​ ​f​r​o​m​ ​r​u​n​t​i​m​e​ ​r​o​u​t​e​s​.
			 */
			description: string
			/**
			 * L​o​c​a​l​ ​f​i​l​e​ ​a​n​d​ ​H​T​T​P​S​ ​U​R​L​ ​s​o​u​r​c​e​s​.
			 */
			itemOneDetail: string
			/**
			 * I​m​p​o​r​t
			 */
			itemOneLabel: string
			/**
			 * R​e​v​e​r​s​i​b​l​e​ ​a​c​t​i​v​a​t​i​o​n​ ​w​i​t​h​ ​e​x​p​l​i​c​i​t​ ​o​u​t​c​o​m​e​s​.
			 */
			itemThreeDetail: string
			/**
			 * A​c​t​i​v​a​t​e
			 */
			itemThreeLabel: string
			/**
			 * C​o​m​p​a​t​i​b​i​l​i​t​y​ ​a​n​d​ ​c​o​n​f​l​i​c​t​ ​p​r​e​f​l​i​g​h​t​.
			 */
			itemTwoDetail: string
			/**
			 * V​a​l​i​d​a​t​e
			 */
			itemTwoLabel: string
			/**
			 * N​o​ ​p​r​o​d​u​c​t​i​o​n​ ​p​r​o​f​i​l​e​ ​s​t​o​r​e​ ​e​x​i​s​t​s​ ​i​n​ ​P​a​r​t​ ​1​.
			 */
			prerequisite: string
			/**
			 * P​r​o​f​i​l​e​s
			 */
			title: string
		}
		traffic: {
			/**
			 * A​c​t​i​v​e​ ​c​o​n​n​e​c​t​i​o​n​s​,​ ​r​e​c​e​n​t​l​y​ ​c​l​o​s​e​d​ ​c​o​n​n​e​c​t​i​o​n​s​,​ ​a​n​d​ ​e​f​f​e​c​t​i​v​e​ ​r​u​l​e​s​ ​w​i​l​l​ ​s​h​a​r​e​ ​o​n​e​ ​i​n​v​e​s​t​i​g​a​t​i​o​n​ ​s​u​r​f​a​c​e​.
			 */
			description: string
			/**
			 * D​e​s​t​i​n​a​t​i​o​n​,​ ​p​r​o​c​e​s​s​,​ ​t​r​a​f​f​i​c​,​ ​r​u​l​e​,​ ​a​n​d​ ​r​o​u​t​e​ ​c​h​a​i​n​.
			 */
			itemOneDetail: string
			/**
			 * A​c​t​i​v​e
			 */
			itemOneLabel: string
			/**
			 * O​r​d​e​r​e​d​,​ ​s​e​a​r​c​h​a​b​l​e​ ​e​f​f​e​c​t​i​v​e​ ​r​u​l​e​ ​r​e​f​e​r​e​n​c​e​.
			 */
			itemThreeDetail: string
			/**
			 * R​u​l​e​s
			 */
			itemThreeLabel: string
			/**
			 * B​o​u​n​d​e​d​ ​l​o​c​a​l​ ​d​i​a​g​n​o​s​t​i​c​ ​h​i​s​t​o​r​y​.
			 */
			itemTwoDetail: string
			/**
			 * C​l​o​s​e​d
			 */
			itemTwoLabel: string
			/**
			 * N​o​ ​c​o​n​n​e​c​t​i​o​n​ ​s​t​r​e​a​m​ ​i​s​ ​a​t​t​a​c​h​e​d​;​ ​S​t​a​t​u​s​ ​v​a​l​u​e​s​ ​r​e​m​a​i​n​ ​f​i​x​t​u​r​e​ ​d​a​t​a​.
			 */
			prerequisite: string
			/**
			 * T​r​a​f​f​i​c
			 */
			title: string
		}
		events: {
			/**
			 * A​p​p​l​i​c​a​t​i​o​n​,​ ​c​o​r​e​,​ ​R​P​C​,​ ​a​n​d​ ​p​l​a​t​f​o​r​m​ ​e​v​e​n​t​s​ ​w​i​l​l​ ​s​u​p​p​o​r​t​ ​c​o​n​t​e​x​t​u​a​l​ ​r​e​c​o​v​e​r​y​ ​a​n​d​ ​g​u​i​d​e​d​ ​d​i​a​g​n​o​s​t​i​c​s​.
			 */
			description: string
			/**
			 * T​i​m​e​s​t​a​m​p​e​d​ ​s​o​u​r​c​e​ ​a​n​d​ ​s​e​v​e​r​i​t​y​ ​r​o​w​s​.
			 */
			itemOneDetail: string
			/**
			 * E​v​e​n​t​ ​s​t​r​e​a​m
			 */
			itemOneLabel: string
			/**
			 * E​x​p​l​i​c​i​t​ ​p​r​e​v​i​e​w​ ​a​n​d​ ​s​t​r​u​c​t​u​r​e​d​ ​r​e​d​a​c​t​i​o​n​.
			 */
			itemThreeDetail: string
			/**
			 * E​x​p​o​r​t
			 */
			itemThreeLabel: string
			/**
			 * L​a​y​e​r​e​d​ ​c​h​e​c​k​s​ ​w​i​t​h​ ​o​b​s​e​r​v​e​d​ ​s​c​o​p​e​.
			 */
			itemTwoDetail: string
			/**
			 * D​i​a​g​n​o​s​t​i​c​s
			 */
			itemTwoLabel: string
			/**
			 * N​o​ ​d​e​s​k​t​o​p​-​b​r​i​d​g​e​ ​e​v​e​n​t​ ​b​u​f​f​e​r​ ​o​r​ ​d​i​a​g​n​o​s​t​i​c​ ​r​u​n​n​e​r​ ​e​x​i​s​t​s​ ​y​e​t​.
			 */
			prerequisite: string
			/**
			 * E​v​e​n​t​s
			 */
			title: string
		}
		settings: {
			/**
			 * S​e​t​t​i​n​g​s​ ​w​i​l​l​ ​b​e​ ​o​r​g​a​n​i​z​e​d​ ​b​y​ ​o​u​t​c​o​m​e​ ​a​n​d​ ​w​i​l​l​ ​e​x​p​o​s​e​ ​o​n​l​y​ ​c​a​p​a​b​i​l​i​t​i​e​s​ ​c​o​n​f​i​r​m​e​d​ ​b​y​ ​t​h​e​ ​p​l​a​t​f​o​r​m​ ​a​d​a​p​t​e​r​.
			 */
			description: string
			/**
			 * S​y​s​t​e​m​ ​P​r​o​x​y​,​ ​f​u​t​u​r​e​ ​T​U​N​ ​s​e​t​u​p​,​ ​a​n​d​ ​s​t​a​r​t​u​p​.
			 */
			itemOneDetail: string
			/**
			 * C​a​p​t​u​r​e​ ​a​n​d​ ​s​t​a​r​t​u​p
			 */
			itemOneLabel: string
			/**
			 * T​h​e​m​e​,​ ​m​o​t​i​o​n​,​ ​u​p​d​a​t​e​,​ ​p​r​i​v​a​c​y​,​ ​a​n​d​ ​s​u​p​p​o​r​t​.
			 */
			itemThreeDetail: string
			/**
			 * A​p​p​l​i​c​a​t​i​o​n
			 */
			itemThreeLabel: string
			/**
			 * C​o​r​e​ ​p​o​l​i​c​y​ ​w​i​t​h​ ​c​l​e​a​r​ ​r​i​s​k​ ​b​o​u​n​d​a​r​i​e​s​.
			 */
			itemTwoDetail: string
			/**
			 * N​e​t​w​o​r​k​ ​a​n​d​ ​D​N​S
			 */
			itemTwoLabel: string
			/**
			 * P​l​a​t​f​o​r​m​ ​c​a​p​a​b​i​l​i​t​i​e​s​ ​a​r​e​ ​f​i​x​t​u​r​e​-​o​n​l​y​ ​i​n​ ​t​h​i​s​ ​p​r​o​d​u​c​t​i​o​n​ ​f​o​u​n​d​a​t​i​o​n​.
			 */
			prerequisite: string
			/**
			 * S​e​t​t​i​n​g​s
			 */
			title: string
		}
	}
	notFound: {
		/**
		 * T​h​i​s​ ​r​o​u​t​e​ ​i​s​ ​n​o​t​ ​o​n​e​ ​o​f​ ​t​h​e​ ​s​i​x​ ​s​t​a​b​l​e​ ​p​r​o​d​u​c​t​ ​d​e​s​t​i​n​a​t​i​o​n​s​.
		 */
		description: string
		/**
		 * R​e​t​u​r​n​ ​t​o​ ​S​t​a​t​u​s
		 */
		returnToStatus: string
		/**
		 * P​a​g​e​ ​n​o​t​ ​f​o​u​n​d
		 */
		title: string
	}
	startupFailure: {
		/**
		 * M​i​s​h​ ​c​o​u​l​d​ ​n​o​t​ ​e​s​t​a​b​l​i​s​h​ ​i​t​s​ ​p​r​i​v​a​t​e​ ​l​o​c​a​l​ ​c​o​n​n​e​c​t​i​o​n​.​ ​N​o​ ​s​y​s​t​e​m​ ​o​r​ ​n​e​t​w​o​r​k​ ​s​t​a​t​e​ ​i​s​ ​b​e​i​n​g​ ​s​h​o​w​n​.
		 */
		description: string
		/**
		 * M​i​s​h​ ​d​e​s​k​t​o​p
		 */
		eyebrow: string
		/**
		 * L​o​c​a​l​ ​s​e​r​v​i​c​e​ ​u​n​a​v​a​i​l​a​b​l​e
		 */
		title: string
	}
	errors: {
		/**
		 * T​h​e​ ​c​o​m​m​a​n​d​ ​f​a​i​l​e​d​.
		 */
		command: string
		/**
		 * U​n​a​b​l​e​ ​t​o​ ​l​o​a​d​ ​S​t​a​t​u​s​ ​d​a​t​a​.
		 */
		loadStatus: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Pending
		 */
		pending: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Unavailable
		 */
		unavailable: () => LocalizedString
	}
	language: {
		/**
		 * Change language. Current language: {language}
		 */
		current: (arg: { language: string }) => LocalizedString
		/**
		 * English
		 */
		english: () => LocalizedString
		/**
		 * Language
		 */
		label: () => LocalizedString
		/**
		 * 简体中文
		 */
		simplifiedChinese: () => LocalizedString
	}
	appearance: {
		/**
		 * Change theme. Current theme: {appearance}
		 */
		current: (arg: { appearance: string }) => LocalizedString
		/**
		 * Dark
		 */
		dark: () => LocalizedString
		/**
		 * Theme
		 */
		label: () => LocalizedString
		/**
		 * Light
		 */
		light: () => LocalizedString
		/**
		 * Follow system
		 */
		system: () => LocalizedString
	}
	navigation: {
		/**
		 * Events
		 */
		events: () => LocalizedString
		/**
		 * Primary navigation
		 */
		primary: () => LocalizedString
		/**
		 * Profiles
		 */
		profiles: () => LocalizedString
		/**
		 * Routes
		 */
		routes: () => LocalizedString
		/**
		 * Workspace sections
		 */
		sections: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Traffic
		 */
		traffic: () => LocalizedString
	}
	toolbar: {
		/**
		 * Status is read from this device.
		 */
		deviceDescription: () => LocalizedString
		/**
		 * Device status
		 */
		deviceMode: () => LocalizedString
		/**
		 * The current screen uses simulated data. No action changes system or network state.
		 */
		demoDescription: () => LocalizedString
		/**
		 * Demo mode
		 */
		demoMode: () => LocalizedString
		/**
		 * This action changes local fixture data only and does not change system or network state.
		 */
		fixtureActionDescription: () => LocalizedString
		/**
		 * Loading local status…
		 */
		loadingDesktop: () => LocalizedString
		/**
		 * Loading fixture…
		 */
		loadingFixture: () => LocalizedString
		/**
		 * Local service
		 */
		localService: () => LocalizedString
		/**
		 * Status is read from Mish's private local desktop service.
		 */
		localServiceDescription: () => LocalizedString
		/**
		 * Profiles
		 */
		profiles: () => LocalizedString
		/**
		 * Switch profile. Current profile: {profile}
		 */
		switchProfile: (arg: { profile: string }) => LocalizedString
	}
	proxyControl: {
		/**
		 * Disable proxy
		 */
		disableAria: () => LocalizedString
		/**
		 * Disable proxy
		 */
		disable: () => LocalizedString
		/**
		 * Disable the proxy demo state
		 */
		disableFixtureAria: () => LocalizedString
		/**
		 * Enable proxy
		 */
		enableAria: () => LocalizedString
		/**
		 * Enable the proxy demo state
		 */
		enableFixtureAria: () => LocalizedString
		/**
		 * Start proxy with {modes}
		 */
		enableWithModes: (arg: { modes: string }) => LocalizedString
		/**
		 * Enable proxy
		 */
		enable: () => LocalizedString
		/**
		 * Proxy needs attention
		 */
		needsAttention: () => LocalizedString
		/**
		 * Proxy running
		 */
		running: () => LocalizedString
	}
	status: {
		/**
		 * Active rules
		 */
		activeRules: () => LocalizedString
		/**
		 * Connections
		 */
		connections: () => LocalizedString
		/**
		 * Current session
		 */
		currentSessionAria: () => LocalizedString
		/**
		 * Live status from the desktop local service.
		 */
		desktopActivity: () => LocalizedString
		/**
		 * Desktop status is unavailable.
		 */
		desktopUnavailable: () => LocalizedString
		/**
		 * Live status from this device.
		 */
		deviceActivity: () => LocalizedString
		/**
		 * Downloaded
		 */
		downloaded: () => LocalizedString
		/**
		 * Fixture activity at a glance.
		 */
		fixtureActivity: () => LocalizedString
		/**
		 * Fixture data is unavailable.
		 */
		fixtureUnavailable: () => LocalizedString
		/**
		 * Groups
		 */
		groups: () => LocalizedString
		/**
		 * Frequently used policy groups
		 */
		groupsAria: () => LocalizedString
		/**
		 * No policy groups available.
		 */
		groupsEmpty: () => LocalizedString
		/**
		 * Connecting to the desktop local service…
		 */
		loadingDesktop: () => LocalizedString
		/**
		 * Loading typed fixture data…
		 */
		loadingFixture: () => LocalizedString
		/**
		 * Memory
		 */
		memory: () => LocalizedString
		/**
		 * Direct
		 */
		modeDirect: () => LocalizedString
		/**
		 * Global
		 */
		modeGlobal: () => LocalizedString
		/**
		 * Rule
		 */
		modeRule: () => LocalizedString
		/**
		 * No selection
		 */
		noSelection: () => LocalizedString
		/**
		 * Open live traffic
		 */
		openLiveTraffic: () => LocalizedString
		/**
		 * Routing mode
		 */
		routingMode: () => LocalizedString
		/**
		 * Reconnecting to the Mish background service. Last confirmed data is stale.
		 */
		reconnecting: () => LocalizedString
		/**
		 * Session
		 */
		session: () => LocalizedString
		/**
		 * Services
		 */
		services: () => LocalizedString
		/**
		 * The Mish background service is disconnected. Last confirmed data is stale.
		 */
		staleData: () => LocalizedString
		/**
		 * Traffic capture
		 */
		trafficCapture: () => LocalizedString
		/**
		 * Uploaded
		 */
		uploaded: () => LocalizedString
		/**
		 * Uptime
		 */
		uptime: () => LocalizedString
		/**
		 * Most used first.
		 */
		usedFirst: () => LocalizedString
		/**
		 * View all
		 */
		viewAll: () => LocalizedString
		/**
		 * {count} available children
		 */
		availableChildren: (arg: { count: number }) => LocalizedString
	}
	capture: {
		/**
		 * Got it
		 */
		acknowledge: () => LocalizedString
		/**
		 * These controls show capture state reported by the local desktop service. A control stays disabled when its capability or action is unavailable.
		 */
		desktopDescription: () => LocalizedString
		/**
		 * These controls show capture state reported by this device. A control stays disabled when its capability or action is unavailable.
		 */
		deviceDescription: () => LocalizedString
		/**
		 * A pressed control means the mode is selected and remembered; a green icon means it is running. The bottom control pauses without forgetting and restores the remembered combination on the next start. This demo does not modify system network configuration.
		 */
		fixtureDescription: () => LocalizedString
		/**
		 * Learn about System Proxy, Virtual Interface, and remembered start options
		 */
		helpAria: () => LocalizedString
		/**
		 * {mode}, {selection}, {runtime}
		 */
		modeAria: (arg: { mode: string, runtime: string, selection: string }) => LocalizedString
		/**
		 * not running
		 */
		notRunning: () => LocalizedString
		/**
		 * not selected
		 */
		notSelected: () => LocalizedString
		/**
		 * running
		 */
		running: () => LocalizedString
		/**
		 * selected
		 */
		selected: () => LocalizedString
		/**
		 * Leave OS settings as is
		 */
		leaveAsIs: () => LocalizedString
		/**
		 * Repair System Proxy
		 */
		repairSystemProxy: () => LocalizedString
		/**
		 * System Proxy
		 */
		systemProxy: () => LocalizedString
		/**
		 * System Proxy is applied and confirmed by macOS.
		 */
		systemProxyApplied: () => LocalizedString
		/**
		 * System Proxy was not enabled because the active profile and Mihomo core are unavailable.
		 */
		systemProxyCoreFailure: () => LocalizedString
		/**
		 * Routes applications that follow the system proxy settings.
		 */
		systemProxyDescription: () => LocalizedString
		/**
		 * System Proxy differs from Mish's requested state. Repair it or leave the current OS settings as is.
		 */
		systemProxyDrift: () => LocalizedString
		/**
		 * System Proxy was not confirmed. The prior state was retained or restored.
		 */
		systemProxyFailure: () => LocalizedString
		/**
		 * Simulates routing applications that follow the system proxy settings.
		 */
		systemProxyFixtureDescription: () => LocalizedString
		/**
		 * Current OS proxy settings are left unchanged and are no longer managed by Mish.
		 */
		systemProxyLeftAsIs: () => LocalizedString
		/**
		 * System Proxy is off and confirmed by macOS.
		 */
		systemProxyOff: () => LocalizedString
		/**
		 * System Proxy is pending macOS confirmation.
		 */
		systemProxyPending: () => LocalizedString
		/**
		 * macOS did not allow the System Proxy change. No success was recorded.
		 */
		systemProxyPermissionFailure: () => LocalizedString
		/**
		 * Automatic or authenticated proxy settings are active. Mish left them unchanged.
		 */
		systemProxyUnsafeFailure: () => LocalizedString
		/**
		 * System Proxy is selected off, but the macOS state is not available.
		 */
		systemProxyUnknown: () => LocalizedString
		/**
		 * System Proxy and Virtual Interface
		 */
		title: () => LocalizedString
		/**
		 * Virtual Interface
		 */
		tun: () => LocalizedString
		/**
		 * Uses a TUN virtual network interface to capture broader traffic.
		 */
		tunDescription: () => LocalizedString
		/**
		 * Simulates a TUN virtual network interface for broader traffic.
		 */
		tunFixtureDescription: () => LocalizedString
	}
	capabilities: {
		/**
		 * A traffic-capture capability requires permission before it can change.
		 */
		capturePermission: () => LocalizedString
		/**
		 * Traffic capture is unavailable on this platform.
		 */
		captureUnavailable: () => LocalizedString
		/**
		 * This action is not supported by the current local service.
		 */
		localActionUnavailable: () => LocalizedString
		/**
		 * System Proxy requires permission before it can change.
		 */
		systemProxyPermission: () => LocalizedString
		/**
		 * System Proxy is unavailable on this platform.
		 */
		systemProxyUnavailable: () => LocalizedString
		/**
		 * Virtual Interface requires permission before it can change.
		 */
		tunPermission: () => LocalizedString
		/**
		 * Virtual Interface is unavailable on this platform.
		 */
		tunUnavailable: () => LocalizedString
	}
	proxyPicker: {
		/**
		 * Select a child for this policy group. The selection is not global.
		 */
		description: () => LocalizedString
		/**
		 * No matching nodes.
		 */
		empty: () => LocalizedString
		/**
		 * Search available nodes
		 */
		searchAria: () => LocalizedString
		/**
		 * Search nodes
		 */
		searchPlaceholder: () => LocalizedString
	}
	routes: {
		/**
		 * Active profile: {profile}
		 */
		activeProfile: (arg: { profile: string }) => LocalizedString
		/**
		 * {count} children
		 */
		childCount: (arg: { count: number }) => LocalizedString
		/**
		 * Collapse {group}
		 */
		collapseGroup: (arg: { group: string }) => LocalizedString
		/**
		 * Configuration
		 */
		configurationOrder: () => LocalizedString
		/**
		 * Current: {child}
		 */
		currentChild: (arg: { child: string }) => LocalizedString
		/**
		 * Browse the active profile's policy-group graph. Every choice remains scoped to its owning selector.
		 */
		description: () => LocalizedString
		/**
		 * Policy groups reported by the desktop local service.
		 */
		desktopDescription: () => LocalizedString
		/**
		 * Policy groups reported by this device.
		 */
		deviceDescription: () => LocalizedString
		/**
		 * Expand {group}
		 */
		expandGroup: (arg: { group: string }) => LocalizedString
		/**
		 * Nested fixture groups for interaction and scale verification.
		 */
		fixtureDescription: () => LocalizedString
		/**
		 * Mish did not render this graph because its relationships are inconsistent. No route choice was changed.
		 */
		graphErrorDescription: () => LocalizedString
		/**
		 * The policy-group graph is invalid
		 */
		graphErrorTitle: () => LocalizedString
		groupType: {
			/**
			 * Direct
			 */
			direct: () => LocalizedString
			/**
			 * Fallback
			 */
			fallback: () => LocalizedString
			/**
			 * Load balance
			 */
			loadBalance: () => LocalizedString
			/**
			 * Reject
			 */
			reject: () => LocalizedString
			/**
			 * Relay
			 */
			relay: () => LocalizedString
			/**
			 * Selector
			 */
			selector: () => LocalizedString
			/**
			 * Unsupported · {type}
			 */
			unsupported: (arg: { type: string }) => LocalizedString
			/**
			 * URL test
			 */
			urlTest: () => LocalizedString
		}
		/**
		 * Cycle detected: {path}
		 */
		invalidCycle: (arg: { path: string }) => LocalizedString
		/**
		 * {group} repeats child {child}.
		 */
		invalidDuplicateChild: (arg: { child: string, group: string }) => LocalizedString
		/**
		 * The ID {entity} is used by more than one entity.
		 */
		invalidDuplicateEntity: (arg: { entity: string }) => LocalizedString
		/**
		 * {group} references missing child {child}.
		 */
		invalidMissingChild: (arg: { child: string, group: string }) => LocalizedString
		/**
		 * {group} reports current child {child} outside the group.
		 */
		invalidSelection: (arg: { child: string, group: string }) => LocalizedString
		/**
		 * {group} is terminal but reports children.
		 */
		invalidTerminalChildren: (arg: { group: string }) => LocalizedString
		/**
		 * Latency
		 */
		latency: () => LocalizedString
		/**
		 * {latency} ms
		 */
		latencyMilliseconds: (arg: { latency: number }) => LocalizedString
		/**
		 * Latency unavailable
		 */
		latencyUnavailable: () => LocalizedString
		/**
		 * Label
		 */
		labelOrder: () => LocalizedString
		/**
		 * This group has no children.
		 */
		noChildren: () => LocalizedString
		/**
		 * No single current child
		 */
		noCurrentChild: () => LocalizedString
		/**
		 * The current adapter did not report any policy groups.
		 */
		noGroupsDescription: () => LocalizedString
		/**
		 * No policy groups
		 */
		noGroupsTitle: () => LocalizedString
		/**
		 * Try another complete group or child label.
		 */
		noMatchesDescription: () => LocalizedString
		/**
		 * No matching routes
		 */
		noMatchesTitle: () => LocalizedString
		/**
		 * The current local service does not support policy-group selection. You can inspect and sort each group, but choices remain disabled.
		 */
		readOnlyDescription: () => LocalizedString
		/**
		 * Routes are read-only
		 */
		readOnlyTitle: () => LocalizedString
		/**
		 * Search policy groups and children
		 */
		searchLabel: () => LocalizedString
		/**
		 * Search complete labels
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Select {child} in {group}
		 */
		selectChild: (arg: { child: string, group: string }) => LocalizedString
		/**
		 * Selected
		 */
		selected: () => LocalizedString
		/**
		 * Sort children in {group}
		 */
		sortChildren: (arg: { group: string }) => LocalizedString
		/**
		 * Routes
		 */
		title: () => LocalizedString
	}
	profiles: {
		/**
		 * Activate
		 */
		activation: () => LocalizedString
		/**
		 * Activation remains disabled until Mish can validate, switch, and roll back the core configuration transactionally.
		 */
		activationUnavailable: () => LocalizedString
		/**
		 * Active
		 */
		active: () => LocalizedString
		/**
		 * The active profile cannot be deleted without a safe replacement or stopped-state transaction.
		 */
		activeDeleteUnavailable: () => LocalizedString
		/**
		 * Failed
		 */
		attemptFailed: () => LocalizedString
		/**
		 * Succeeded
		 */
		attemptSucceeded: () => LocalizedString
		/**
		 * Checking…
		 */
		checking: () => LocalizedString
		/**
		 * Disabled: {count}
		 */
		classificationDisabled: (arg: { count: number }) => LocalizedString
		/**
		 * Overridden: {count}
		 */
		classificationOverridden: (arg: { count: number }) => LocalizedString
		/**
		 * Preserved: {count}
		 */
		classificationPreserved: (arg: { count: number }) => LocalizedString
		/**
		 * Rejected: {count}
		 */
		classificationRejected: (arg: { count: number }) => LocalizedString
		/**
		 * Ownership changes
		 */
		classifications: () => LocalizedString
		/**
		 * This removes the source, immutable revisions, normalized artifacts, and profile-scoped local state.
		 */
		deleteDescription: () => LocalizedString
		/**
		 * The profile could not be deleted.
		 */
		deleteFailed: () => LocalizedString
		/**
		 * Delete {profile}?
		 */
		deleteTitle: (arg: { profile: string }) => LocalizedString
		/**
		 * Profile deleted
		 */
		deletedToast: () => LocalizedString
		/**
		 * Validate and store Mihomo profile sources without changing the running core configuration.
		 */
		description: () => LocalizedString
		/**
		 * Profiles are stored privately in Mish app data. HTTPS import and manual refresh use the authenticated local service.
		 */
		desktopDescription: () => LocalizedString
		/**
		 * Import an HTTPS source or choose a local YAML file to begin.
		 */
		emptyDescription: () => LocalizedString
		/**
		 * No saved profiles
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Latest attempt failed
		 */
		error: () => LocalizedString
		/**
		 * This browser-only view uses fictional metadata. Import, refresh, save, delete, and local file access are unavailable.
		 */
		fixtureDescription: () => LocalizedString
		/**
		 * Groups
		 */
		groups: () => LocalizedString
		/**
		 * The complete URL is sent only to the authenticated local service and is never shown again after preflight.
		 */
		httpsDescription: () => LocalizedString
		/**
		 * HTTPS profile URL
		 */
		httpsLabel: () => LocalizedString
		/**
		 * Preflight checks size, transport, YAML structure, and application/platform ownership before anything is saved.
		 */
		importDescription: () => LocalizedString
		/**
		 * Profile preflight failed. No profile was saved or activated.
		 */
		importFailed: () => LocalizedString
		/**
		 * Import HTTPS
		 */
		importHttps: () => LocalizedString
		/**
		 * Choose local file
		 */
		importLocal: () => LocalizedString
		/**
		 * Import profile
		 */
		importTitle: () => LocalizedString
		/**
		 * Optional. If empty, Mish uses a safe source-derived label.
		 */
		labelDescription: () => LocalizedString
		/**
		 * Profile label
		 */
		labelLabel: () => LocalizedString
		/**
		 * Last attempt
		 */
		lastAttempt: () => LocalizedString
		/**
		 * Last known valid retained
		 */
		lastKnownValid: () => LocalizedString
		/**
		 * Last success
		 */
		lastSuccess: () => LocalizedString
		/**
		 * Loading profiles…
		 */
		loading: () => LocalizedString
		/**
		 * Local files can only be opened through the native picker after an explicit user choice.
		 */
		localPermission: () => LocalizedString
		/**
		 * Never
		 */
		never: () => LocalizedString
		/**
		 * This summary contains no source YAML, credentials, complete local path, or raw subscription URL.
		 */
		previewDescription: () => LocalizedString
		/**
		 * Ready to save
		 */
		previewTitle: () => LocalizedString
		/**
		 * Preview
		 */
		preflight: () => LocalizedString
		/**
		 * Saved profiles
		 */
		profilesAria: () => LocalizedString
		/**
		 * Proxies
		 */
		proxies: () => LocalizedString
		/**
		 * Refresh
		 */
		refresh: () => LocalizedString
		/**
		 * Refresh failed. The last known valid revision remains stored.
		 */
		refreshFailed: () => LocalizedString
		/**
		 * Refreshing…
		 */
		refreshing: () => LocalizedString
		/**
		 * Rules
		 */
		rules: () => LocalizedString
		/**
		 * The validated profile could not be saved.
		 */
		saveFailed: () => LocalizedString
		/**
		 * Profile saved
		 */
		savedToast: () => LocalizedString
		/**
		 * Save profile
		 */
		saveProfile: () => LocalizedString
		/**
		 * Saving…
		 */
		saving: () => LocalizedString
		/**
		 * Sensitive source or configuration data will stay in Mish's private app-data storage.
		 */
		sensitiveNotice: () => LocalizedString
		/**
		 * Source
		 */
		source: () => LocalizedString
		/**
		 * HTTPS
		 */
		sourceHttps: () => LocalizedString
		/**
		 * Local file
		 */
		sourceLocal: () => LocalizedString
		/**
		 * Stale
		 */
		stale: () => LocalizedString
		/**
		 * Profiles
		 */
		title: () => LocalizedString
		/**
		 * Valid
		 */
		valid: () => LocalizedString
		/**
		 * Review warnings
		 */
		warning: () => LocalizedString
		/**
		 * Warnings: {count}
		 */
		warnings: (arg: { count: number }) => LocalizedString
	}
	services: {
		/**
		 * Add service
		 */
		add: () => LocalizedString
		/**
		 * Demo service added
		 */
		addedToast: () => LocalizedString
		/**
		 * Default demo services restored
		 */
		defaultRestoredToast: () => LocalizedString
		/**
		 * This removes only the local fixture monitor.
		 */
		deleteDescription: () => LocalizedString
		/**
		 * Delete {service}?
		 */
		deleteTitle: (arg: { service: string }) => LocalizedString
		/**
		 * Edit service
		 */
		edit: () => LocalizedString
		/**
		 * Service details:
		 */
		editAria: () => LocalizedString
		/**
		 * The local desktop service reports no service monitors.
		 */
		desktopEmptyDescription: () => LocalizedString
		/**
		 * Endpoint status reported by the local desktop service.
		 */
		desktopEndpointDescription: () => LocalizedString
		/**
		 * No service monitors
		 */
		empty: () => LocalizedString
		/**
		 * Add a local demo monitor. No request will be sent.
		 */
		fixtureEmptyDescription: () => LocalizedString
		/**
		 * Fixture endpoint latency.
		 */
		fixtureEndpointDescription: () => LocalizedString
		/**
		 * Enter a title.
		 */
		labelError: () => LocalizedString
		/**
		 * Manage
		 */
		manage: () => LocalizedString
		/**
		 * Fixture metadata only. Part 1 never requests this endpoint.
		 */
		metadataDescription: () => LocalizedString
		/**
		 * Probe URL
		 */
		probeUrl: () => LocalizedString
		/**
		 * Demo service removed
		 */
		removedToast: () => LocalizedString
		/**
		 * Restore defaults
		 */
		restoreDefaults: () => LocalizedString
		/**
		 * Service name
		 */
		serviceName: () => LocalizedString
		/**
		 * Title
		 */
		title: () => LocalizedString
		/**
		 * Demo service updated
		 */
		updatedToast: () => LocalizedString
		/**
		 * Only HTTP and HTTPS metadata is accepted by the fixture adapter.
		 */
		urlDescription: () => LocalizedString
		/**
		 * Enter a valid HTTP or HTTPS URL.
		 */
		urlError: () => LocalizedString
		/**
		 * Service latency monitors
		 */
		aria: () => LocalizedString
		/**
		 * this service
		 */
		fallbackName: () => LocalizedString
	}
	traffic: {
		/**
		 * Active
		 */
		active: () => LocalizedString
		/**
		 * No active connections
		 */
		activeEmpty: () => LocalizedString
		/**
		 * The current snapshot contains no active connections.
		 */
		activeEmptyDescription: () => LocalizedString
		/**
		 * All networks
		 */
		allNetworks: () => LocalizedString
		/**
		 * Clear Closed
		 */
		clearClosed: () => LocalizedString
		/**
		 * Clears only this app's bounded local history. Active connections and Mihomo state are unchanged.
		 */
		clearClosedDescription: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Close all
		 */
		closeAll: () => LocalizedString
		/**
		 * Real connection-close commands are not included in this read-only slice. No command will be sent.
		 */
		closeDisabled: () => LocalizedString
		/**
		 * Closed
		 */
		closed: () => LocalizedString
		/**
		 * Closed
		 */
		closedAt: () => LocalizedString
		/**
		 * No recently closed connections
		 */
		closedEmpty: () => LocalizedString
		/**
		 * Connections closed during this uninterrupted local observation session appear here for up to 30 minutes, limited to 512 rows.
		 */
		closedEmptyDescription: () => LocalizedString
		/**
		 * Connection details
		 */
		connectionDetails: () => LocalizedString
		/**
		 * Destination
		 */
		destination: () => LocalizedString
		/**
		 * Destination host
		 */
		destinationHost: () => LocalizedString
		/**
		 * Destination IP
		 */
		destinationIp: () => LocalizedString
		/**
		 * Complete locally observed connection metadata and ordered route chain.
		 */
		detailDescription: () => LocalizedString
		/**
		 * Disabled
		 */
		disabled: () => LocalizedString
		/**
		 * Downloaded
		 */
		download: () => LocalizedString
		/**
		 * Enabled
		 */
		enabled: () => LocalizedString
		/**
		 * Fictional local fixture data. No network or system action is performed.
		 */
		fixtureNotice: () => LocalizedString
		/**
		 * Hits
		 */
		hits: () => LocalizedString
		/**
		 * Read-only observations from the desktop local service.
		 */
		liveNotice: () => LocalizedString
		/**
		 * Traffic data could not be loaded.
		 */
		loadError: () => LocalizedString
		/**
		 * Show more
		 */
		loadMore: () => LocalizedString
		/**
		 * Network
		 */
		network: () => LocalizedString
		/**
		 * No matches
		 */
		noMatches: () => LocalizedString
		/**
		 * Clear or change the text and structured filters.
		 */
		noMatchesDescription: () => LocalizedString
		/**
		 * Ordered route chain
		 */
		orderedChain: () => LocalizedString
		/**
		 * Payload
		 */
		payload: () => LocalizedString
		/**
		 * Priority
		 */
		priority: () => LocalizedString
		/**
		 * Process
		 */
		process: () => LocalizedString
		/**
		 * Process path
		 */
		processPath: () => LocalizedString
		/**
		 * Profile {profile}
		 */
		profile: (arg: { profile: string }) => LocalizedString
		/**
		 * Protocol
		 */
		protocol: () => LocalizedString
		/**
		 * Provider chain
		 */
		providerChain: () => LocalizedString
		/**
		 * Observation session {session}; reconnects {count}
		 */
		reconnect: (arg: { count: number, session: string }) => LocalizedString
		/**
		 * Local Closed retention: 30 minutes / 512 rows
		 */
		retention: () => LocalizedString
		/**
		 * Route
		 */
		route: () => LocalizedString
		/**
		 * Remote destination
		 */
		remoteDestination: () => LocalizedString
		/**
		 * Matched rule
		 */
		rule: () => LocalizedString
		/**
		 * Rules
		 */
		rules: () => LocalizedString
		/**
		 * No effective rules
		 */
		rulesEmpty: () => LocalizedString
		/**
		 * The current Traffic snapshot contains no rules.
		 */
		rulesEmptyDescription: () => LocalizedString
		/**
		 * Search Traffic
		 */
		searchLabel: () => LocalizedString
		/**
		 * Search, or use destination:, process:, rule:, chain:, network:, protocol:, state:
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Showing {visible} of {total}
		 */
		showing: (arg: { total: number, visible: number }) => LocalizedString
		/**
		 * Destination
		 */
		sortDestination: () => LocalizedString
		/**
		 * Downloaded
		 */
		sortDownload: () => LocalizedString
		/**
		 * Hits
		 */
		sortHits: () => LocalizedString
		/**
		 * Sort
		 */
		sortLabel: () => LocalizedString
		/**
		 * Priority
		 */
		sortPriority: () => LocalizedString
		/**
		 * Started
		 */
		sortStarted: () => LocalizedString
		/**
		 * Target
		 */
		sortTarget: () => LocalizedString
		/**
		 * Type
		 */
		sortType: () => LocalizedString
		/**
		 * Uploaded
		 */
		sortUpload: () => LocalizedString
		/**
		 * Source
		 */
		source: () => LocalizedString
		/**
		 * Sniffed host
		 */
		sniffHost: () => LocalizedString
		/**
		 * Traffic observation is stale after a connection gap. Active rows are hidden until a fresh snapshot establishes a new session.
		 */
		staleNotice: () => LocalizedString
		/**
		 * Started
		 */
		started: () => LocalizedString
		/**
		 * State
		 */
		state: () => LocalizedString
		/**
		 * Target
		 */
		target: () => LocalizedString
		/**
		 * Traffic
		 */
		title: () => LocalizedString
		/**
		 * Unavailable
		 */
		unavailable: () => LocalizedString
		/**
		 * The desktop local service has no configured Traffic observation source. No active state is claimed.
		 */
		unavailableNotice: () => LocalizedString
		/**
		 * Uploaded
		 */
		upload: () => LocalizedString
	}
	destination: {
		/**
		 * Current state
		 */
		currentState: () => LocalizedString
		/**
		 * Production foundation
		 */
		foundation: () => LocalizedString
		/**
		 * Part 2+
		 */
		partTwo: () => LocalizedString
		/**
		 * Stable page ownership, without simulated functionality.
		 */
		plannedDescription: () => LocalizedString
		/**
		 * Planned structure
		 */
		plannedStructure: () => LocalizedString
		routes: {
			/**
			 * The complete policy-group hierarchy will live here without flattening groups into a global node list.
			 */
			description: () => LocalizedString
			/**
			 * Preserve nested selectors and strategy groups.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Group tree
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Run cancellable group- and child-scoped checks.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Latency
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Match complete opaque Unicode labels.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Search
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * Waiting for typed policy-group DTOs from the Part 2 Mish background service.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Routes
			 */
			title: () => LocalizedString
		}
		profiles: {
			/**
			 * Profile sources, validation, activation, and last-known-good state will remain separate from runtime routes.
			 */
			description: () => LocalizedString
			/**
			 * Local file and HTTPS URL sources.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Import
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Reversible activation with explicit outcomes.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Activate
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Compatibility and conflict preflight.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Validate
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * No production profile store exists in Part 1.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Profiles
			 */
			title: () => LocalizedString
		}
		traffic: {
			/**
			 * Active connections, recently closed connections, and effective rules will share one investigation surface.
			 */
			description: () => LocalizedString
			/**
			 * Destination, process, traffic, rule, and route chain.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Active
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Ordered, searchable effective rule reference.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Rules
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Bounded local diagnostic history.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Closed
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * No connection stream is attached; Status values remain fixture data.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Traffic
			 */
			title: () => LocalizedString
		}
		events: {
			/**
			 * Application, core, RPC, and platform events will support contextual recovery and guided diagnostics.
			 */
			description: () => LocalizedString
			/**
			 * Timestamped source and severity rows.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Event stream
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Explicit preview and structured redaction.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Export
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Layered checks with observed scope.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Diagnostics
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * No desktop-bridge event buffer or diagnostic runner exists yet.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Events
			 */
			title: () => LocalizedString
		}
		settings: {
			/**
			 * Settings will be organized by outcome and will expose only capabilities confirmed by the platform adapter.
			 */
			description: () => LocalizedString
			/**
			 * System Proxy, future TUN setup, and startup.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Capture and startup
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Theme, motion, update, privacy, and support.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Application
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Core policy with clear risk boundaries.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Network and DNS
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * Platform capabilities are fixture-only in this production foundation.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Settings
			 */
			title: () => LocalizedString
		}
	}
	notFound: {
		/**
		 * This route is not one of the six stable product destinations.
		 */
		description: () => LocalizedString
		/**
		 * Return to Status
		 */
		returnToStatus: () => LocalizedString
		/**
		 * Page not found
		 */
		title: () => LocalizedString
	}
	startupFailure: {
		/**
		 * Mish could not establish its private local connection. No system or network state is being shown.
		 */
		description: () => LocalizedString
		/**
		 * Mish desktop
		 */
		eyebrow: () => LocalizedString
		/**
		 * Local service unavailable
		 */
		title: () => LocalizedString
	}
	errors: {
		/**
		 * The command failed.
		 */
		command: () => LocalizedString
		/**
		 * Unable to load Status data.
		 */
		loadStatus: () => LocalizedString
	}
}

export type Formatters = {}
