// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * P​e​n​d​i​n​g
		 */
		pending: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * U​n​a​v​a​i​l​a​b​l​e
		 */
		unavailable: string
	}
	language: {
		/**
		 * C​h​a​n​g​e​ ​l​a​n​g​u​a​g​e​.​ ​C​u​r​r​e​n​t​ ​l​a​n​g​u​a​g​e​:​ ​{​l​a​n​g​u​a​g​e​}
		 * @param {string} language
		 */
		current: RequiredParams<'language'>
		/**
		 * E​n​g​l​i​s​h
		 */
		english: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		label: string
		/**
		 * 简​体​中​文
		 */
		simplifiedChinese: string
	}
	navigation: {
		/**
		 * E​v​e​n​t​s
		 */
		events: string
		/**
		 * P​r​i​m​a​r​y​ ​n​a​v​i​g​a​t​i​o​n
		 */
		primary: string
		/**
		 * P​r​o​f​i​l​e​s
		 */
		profiles: string
		/**
		 * R​o​u​t​e​s
		 */
		routes: string
		/**
		 * W​o​r​k​s​p​a​c​e​ ​s​e​c​t​i​o​n​s
		 */
		sections: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * T​r​a​f​f​i​c
		 */
		traffic: string
	}
	toolbar: {
		/**
		 * T​h​e​ ​c​u​r​r​e​n​t​ ​s​c​r​e​e​n​ ​u​s​e​s​ ​s​i​m​u​l​a​t​e​d​ ​d​a​t​a​.​ ​N​o​ ​a​c​t​i​o​n​ ​c​h​a​n​g​e​s​ ​s​y​s​t​e​m​ ​o​r​ ​n​e​t​w​o​r​k​ ​s​t​a​t​e​.
		 */
		demoDescription: string
		/**
		 * D​e​m​o​ ​m​o​d​e
		 */
		demoMode: string
		/**
		 * T​h​i​s​ ​a​c​t​i​o​n​ ​c​h​a​n​g​e​s​ ​l​o​c​a​l​ ​f​i​x​t​u​r​e​ ​d​a​t​a​ ​o​n​l​y​ ​a​n​d​ ​d​o​e​s​ ​n​o​t​ ​c​h​a​n​g​e​ ​s​y​s​t​e​m​ ​o​r​ ​n​e​t​w​o​r​k​ ​s​t​a​t​e​.
		 */
		fixtureActionDescription: string
		/**
		 * L​o​a​d​i​n​g​ ​f​i​x​t​u​r​e​…
		 */
		loadingFixture: string
		/**
		 * P​r​o​f​i​l​e​s
		 */
		profiles: string
		/**
		 * S​w​i​t​c​h​ ​p​r​o​f​i​l​e​.​ ​C​u​r​r​e​n​t​ ​p​r​o​f​i​l​e​:​ ​{​p​r​o​f​i​l​e​}
		 * @param {string} profile
		 */
		switchProfile: RequiredParams<'profile'>
	}
	proxyControl: {
		/**
		 * D​i​s​a​b​l​e​ ​t​h​e​ ​p​r​o​x​y​ ​d​e​m​o​ ​s​t​a​t​e
		 */
		disableAria: string
		/**
		 * D​i​s​a​b​l​e​ ​p​r​o​x​y
		 */
		disable: string
		/**
		 * E​n​a​b​l​e​ ​t​h​e​ ​p​r​o​x​y​ ​d​e​m​o​ ​s​t​a​t​e
		 */
		enableAria: string
		/**
		 * E​n​a​b​l​e​ ​p​r​o​x​y
		 */
		enable: string
		/**
		 * P​r​o​x​y​ ​r​u​n​n​i​n​g
		 */
		running: string
	}
	status: {
		/**
		 * A​c​t​i​v​e​ ​r​u​l​e​s
		 */
		activeRules: string
		/**
		 * C​o​n​n​e​c​t​i​o​n​s
		 */
		connections: string
		/**
		 * C​u​r​r​e​n​t​ ​s​e​s​s​i​o​n
		 */
		currentSessionAria: string
		/**
		 * D​o​w​n​l​o​a​d​e​d
		 */
		downloaded: string
		/**
		 * F​i​x​t​u​r​e​ ​a​c​t​i​v​i​t​y​ ​a​t​ ​a​ ​g​l​a​n​c​e​.
		 */
		fixtureActivity: string
		/**
		 * F​i​x​t​u​r​e​ ​d​a​t​a​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e​.
		 */
		fixtureUnavailable: string
		/**
		 * G​r​o​u​p​s
		 */
		groups: string
		/**
		 * F​r​e​q​u​e​n​t​l​y​ ​u​s​e​d​ ​p​o​l​i​c​y​ ​g​r​o​u​p​s
		 */
		groupsAria: string
		/**
		 * L​o​a​d​i​n​g​ ​t​y​p​e​d​ ​f​i​x​t​u​r​e​ ​d​a​t​a​…
		 */
		loading: string
		/**
		 * M​e​m​o​r​y
		 */
		memory: string
		/**
		 * D​i​r​e​c​t
		 */
		modeDirect: string
		/**
		 * G​l​o​b​a​l
		 */
		modeGlobal: string
		/**
		 * R​u​l​e
		 */
		modeRule: string
		/**
		 * N​o​ ​s​e​l​e​c​t​i​o​n
		 */
		noSelection: string
		/**
		 * O​p​e​n​ ​l​i​v​e​ ​t​r​a​f​f​i​c
		 */
		openLiveTraffic: string
		/**
		 * R​o​u​t​i​n​g​ ​m​o​d​e
		 */
		routingMode: string
		/**
		 * R​e​c​o​n​n​e​c​t​i​n​g​ ​t​o​ ​t​h​e​ ​l​o​c​a​l​ ​a​g​e​n​t​.​ ​L​a​s​t​ ​c​o​n​f​i​r​m​e​d​ ​d​a​t​a​ ​i​s​ ​s​t​a​l​e​.
		 */
		reconnecting: string
		/**
		 * S​e​s​s​i​o​n
		 */
		session: string
		/**
		 * S​e​r​v​i​c​e​s
		 */
		services: string
		/**
		 * T​h​e​ ​l​o​c​a​l​ ​a​g​e​n​t​ ​i​s​ ​d​i​s​c​o​n​n​e​c​t​e​d​.​ ​L​a​s​t​ ​c​o​n​f​i​r​m​e​d​ ​d​a​t​a​ ​i​s​ ​s​t​a​l​e​.
		 */
		staleData: string
		/**
		 * T​r​a​f​f​i​c​ ​c​a​p​t​u​r​e
		 */
		trafficCapture: string
		/**
		 * U​p​l​o​a​d​e​d
		 */
		uploaded: string
		/**
		 * U​p​t​i​m​e
		 */
		uptime: string
		/**
		 * M​o​s​t​ ​u​s​e​d​ ​f​i​r​s​t​.
		 */
		usedFirst: string
		/**
		 * V​i​e​w​ ​a​l​l
		 */
		viewAll: string
		/**
		 * {​c​o​u​n​t​}​ ​a​v​a​i​l​a​b​l​e​ ​c​h​i​l​d​r​e​n
		 * @param {number} count
		 */
		availableChildren: RequiredParams<'count'>
	}
	capture: {
		/**
		 * G​o​t​ ​i​t
		 */
		acknowledge: string
		/**
		 * T​h​i​s​ ​c​h​a​n​g​e​s​ ​f​i​x​t​u​r​e​ ​s​t​a​t​e​ ​o​n​l​y​ ​a​n​d​ ​d​o​e​s​ ​n​o​t​ ​m​o​d​i​f​y​ ​t​h​e​ ​s​y​s​t​e​m​ ​n​e​t​w​o​r​k​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​.
		 */
		description: string
		/**
		 * L​e​a​r​n​ ​t​h​e​ ​d​i​f​f​e​r​e​n​c​e​ ​b​e​t​w​e​e​n​ ​S​y​s​t​e​m​ ​P​r​o​x​y​ ​a​n​d​ ​E​n​h​a​n​c​e​d​ ​M​o​d​e
		 */
		helpAria: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y
		 */
		systemProxy: string
		/**
		 * F​o​r​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​t​h​a​t​ ​f​o​l​l​o​w​ ​s​y​s​t​e​m​ ​p​r​o​x​y​ ​s​e​t​t​i​n​g​s​.​ ​P​a​r​t​ ​2​ ​w​i​l​l​ ​p​r​o​v​i​d​e​ ​t​h​e​ ​r​e​a​l​ ​c​a​p​a​b​i​l​i​t​y​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​p​l​a​t​f​o​r​m​ ​a​d​a​p​t​e​r​.
		 */
		systemProxyDescription: string
		/**
		 * S​y​s​t​e​m​ ​P​r​o​x​y​ ​a​n​d​ ​E​n​h​a​n​c​e​d​ ​M​o​d​e
		 */
		title: string
		/**
		 * E​n​h​a​n​c​e​d​ ​M​o​d​e​ ​(​T​U​N​)
		 */
		tun: string
		/**
		 * A​ ​f​u​t​u​r​e​ ​c​o​n​t​r​o​l​l​e​d​ ​n​a​t​i​v​e​ ​c​a​p​a​b​i​l​i​t​y​ ​w​i​l​l​ ​c​a​p​t​u​r​e​ ​b​r​o​a​d​e​r​ ​t​r​a​f​f​i​c​.​ ​P​a​r​t​ ​1​ ​i​n​s​t​a​l​l​s​ ​n​o​ ​p​e​r​m​i​s​s​i​o​n​ ​a​n​d​ ​p​e​r​f​o​r​m​s​ ​n​o​ ​n​e​t​w​o​r​k​ ​o​p​e​r​a​t​i​o​n​.
		 */
		tunDescription: string
	}
	proxyPicker: {
		/**
		 * S​e​l​e​c​t​ ​a​ ​c​h​i​l​d​ ​f​o​r​ ​t​h​i​s​ ​p​o​l​i​c​y​ ​g​r​o​u​p​.​ ​T​h​e​ ​s​e​l​e​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​g​l​o​b​a​l​.
		 */
		description: string
		/**
		 * N​o​ ​m​a​t​c​h​i​n​g​ ​n​o​d​e​s​.
		 */
		empty: string
		/**
		 * S​e​a​r​c​h​ ​a​v​a​i​l​a​b​l​e​ ​n​o​d​e​s
		 */
		searchAria: string
		/**
		 * S​e​a​r​c​h​ ​n​o​d​e​s
		 */
		searchPlaceholder: string
	}
	services: {
		/**
		 * A​d​d​ ​s​e​r​v​i​c​e
		 */
		add: string
		/**
		 * A​d​d​ ​a​ ​l​o​c​a​l​ ​d​e​m​o​ ​m​o​n​i​t​o​r​.​ ​N​o​ ​r​e​q​u​e​s​t​ ​w​i​l​l​ ​b​e​ ​s​e​n​t​.
		 */
		addDescription: string
		/**
		 * D​e​m​o​ ​s​e​r​v​i​c​e​ ​a​d​d​e​d
		 */
		addedToast: string
		/**
		 * D​e​f​a​u​l​t​ ​d​e​m​o​ ​s​e​r​v​i​c​e​s​ ​r​e​s​t​o​r​e​d
		 */
		defaultRestoredToast: string
		/**
		 * T​h​i​s​ ​r​e​m​o​v​e​s​ ​o​n​l​y​ ​t​h​e​ ​l​o​c​a​l​ ​f​i​x​t​u​r​e​ ​m​o​n​i​t​o​r​.
		 */
		deleteDescription: string
		/**
		 * D​e​l​e​t​e​ ​{​s​e​r​v​i​c​e​}​?
		 * @param {string} service
		 */
		deleteTitle: RequiredParams<'service'>
		/**
		 * E​d​i​t​ ​s​e​r​v​i​c​e
		 */
		edit: string
		/**
		 * E​d​i​t​ ​f​i​x​t​u​r​e​ ​m​o​n​i​t​o​r​:
		 */
		editAria: string
		/**
		 * N​o​ ​f​i​x​t​u​r​e​ ​s​e​r​v​i​c​e​ ​m​o​n​i​t​o​r​s
		 */
		empty: string
		/**
		 * F​i​x​t​u​r​e​ ​e​n​d​p​o​i​n​t​ ​l​a​t​e​n​c​y​.
		 */
		endpointDescription: string
		/**
		 * E​n​t​e​r​ ​a​ ​t​i​t​l​e​.
		 */
		labelError: string
		/**
		 * M​a​n​a​g​e
		 */
		manage: string
		/**
		 * F​i​x​t​u​r​e​ ​m​e​t​a​d​a​t​a​ ​o​n​l​y​.​ ​P​a​r​t​ ​1​ ​n​e​v​e​r​ ​r​e​q​u​e​s​t​s​ ​t​h​i​s​ ​e​n​d​p​o​i​n​t​.
		 */
		metadataDescription: string
		/**
		 * P​r​o​b​e​ ​U​R​L
		 */
		probeUrl: string
		/**
		 * D​e​m​o​ ​s​e​r​v​i​c​e​ ​r​e​m​o​v​e​d
		 */
		removedToast: string
		/**
		 * R​e​s​t​o​r​e​ ​d​e​f​a​u​l​t​s
		 */
		restoreDefaults: string
		/**
		 * S​e​r​v​i​c​e​ ​n​a​m​e
		 */
		serviceName: string
		/**
		 * T​i​t​l​e
		 */
		title: string
		/**
		 * D​e​m​o​ ​s​e​r​v​i​c​e​ ​u​p​d​a​t​e​d
		 */
		updatedToast: string
		/**
		 * O​n​l​y​ ​H​T​T​P​ ​a​n​d​ ​H​T​T​P​S​ ​m​e​t​a​d​a​t​a​ ​i​s​ ​a​c​c​e​p​t​e​d​ ​b​y​ ​t​h​e​ ​f​i​x​t​u​r​e​ ​a​d​a​p​t​e​r​.
		 */
		urlDescription: string
		/**
		 * E​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​H​T​T​P​ ​o​r​ ​H​T​T​P​S​ ​U​R​L​.
		 */
		urlError: string
		/**
		 * S​e​r​v​i​c​e​ ​l​a​t​e​n​c​y​ ​m​o​n​i​t​o​r​s
		 */
		aria: string
		/**
		 * t​h​i​s​ ​s​e​r​v​i​c​e
		 */
		fallbackName: string
	}
	destination: {
		/**
		 * C​u​r​r​e​n​t​ ​s​t​a​t​e
		 */
		currentState: string
		/**
		 * P​r​o​d​u​c​t​i​o​n​ ​f​o​u​n​d​a​t​i​o​n
		 */
		foundation: string
		/**
		 * P​a​r​t​ ​2​+
		 */
		partTwo: string
		/**
		 * S​t​a​b​l​e​ ​p​a​g​e​ ​o​w​n​e​r​s​h​i​p​,​ ​w​i​t​h​o​u​t​ ​s​i​m​u​l​a​t​e​d​ ​f​u​n​c​t​i​o​n​a​l​i​t​y​.
		 */
		plannedDescription: string
		/**
		 * P​l​a​n​n​e​d​ ​s​t​r​u​c​t​u​r​e
		 */
		plannedStructure: string
		routes: {
			/**
			 * T​h​e​ ​c​o​m​p​l​e​t​e​ ​p​o​l​i​c​y​-​g​r​o​u​p​ ​h​i​e​r​a​r​c​h​y​ ​w​i​l​l​ ​l​i​v​e​ ​h​e​r​e​ ​w​i​t​h​o​u​t​ ​f​l​a​t​t​e​n​i​n​g​ ​g​r​o​u​p​s​ ​i​n​t​o​ ​a​ ​g​l​o​b​a​l​ ​n​o​d​e​ ​l​i​s​t​.
			 */
			description: string
			/**
			 * P​r​e​s​e​r​v​e​ ​n​e​s​t​e​d​ ​s​e​l​e​c​t​o​r​s​ ​a​n​d​ ​s​t​r​a​t​e​g​y​ ​g​r​o​u​p​s​.
			 */
			itemOneDetail: string
			/**
			 * G​r​o​u​p​ ​t​r​e​e
			 */
			itemOneLabel: string
			/**
			 * R​u​n​ ​c​a​n​c​e​l​l​a​b​l​e​ ​g​r​o​u​p​-​ ​a​n​d​ ​c​h​i​l​d​-​s​c​o​p​e​d​ ​c​h​e​c​k​s​.
			 */
			itemThreeDetail: string
			/**
			 * L​a​t​e​n​c​y
			 */
			itemThreeLabel: string
			/**
			 * M​a​t​c​h​ ​c​o​m​p​l​e​t​e​ ​o​p​a​q​u​e​ ​U​n​i​c​o​d​e​ ​l​a​b​e​l​s​.
			 */
			itemTwoDetail: string
			/**
			 * S​e​a​r​c​h
			 */
			itemTwoLabel: string
			/**
			 * W​a​i​t​i​n​g​ ​f​o​r​ ​t​y​p​e​d​ ​p​o​l​i​c​y​-​g​r​o​u​p​ ​D​T​O​s​ ​f​r​o​m​ ​t​h​e​ ​P​a​r​t​ ​2​ ​l​o​c​a​l​ ​a​g​e​n​t​.
			 */
			prerequisite: string
			/**
			 * R​o​u​t​e​s
			 */
			title: string
		}
		profiles: {
			/**
			 * P​r​o​f​i​l​e​ ​s​o​u​r​c​e​s​,​ ​v​a​l​i​d​a​t​i​o​n​,​ ​a​c​t​i​v​a​t​i​o​n​,​ ​a​n​d​ ​l​a​s​t​-​k​n​o​w​n​-​g​o​o​d​ ​s​t​a​t​e​ ​w​i​l​l​ ​r​e​m​a​i​n​ ​s​e​p​a​r​a​t​e​ ​f​r​o​m​ ​r​u​n​t​i​m​e​ ​r​o​u​t​e​s​.
			 */
			description: string
			/**
			 * L​o​c​a​l​ ​f​i​l​e​ ​a​n​d​ ​H​T​T​P​S​ ​U​R​L​ ​s​o​u​r​c​e​s​.
			 */
			itemOneDetail: string
			/**
			 * I​m​p​o​r​t
			 */
			itemOneLabel: string
			/**
			 * R​e​v​e​r​s​i​b​l​e​ ​a​c​t​i​v​a​t​i​o​n​ ​w​i​t​h​ ​e​x​p​l​i​c​i​t​ ​o​u​t​c​o​m​e​s​.
			 */
			itemThreeDetail: string
			/**
			 * A​c​t​i​v​a​t​e
			 */
			itemThreeLabel: string
			/**
			 * C​o​m​p​a​t​i​b​i​l​i​t​y​ ​a​n​d​ ​c​o​n​f​l​i​c​t​ ​p​r​e​f​l​i​g​h​t​.
			 */
			itemTwoDetail: string
			/**
			 * V​a​l​i​d​a​t​e
			 */
			itemTwoLabel: string
			/**
			 * N​o​ ​p​r​o​d​u​c​t​i​o​n​ ​p​r​o​f​i​l​e​ ​s​t​o​r​e​ ​e​x​i​s​t​s​ ​i​n​ ​P​a​r​t​ ​1​.
			 */
			prerequisite: string
			/**
			 * P​r​o​f​i​l​e​s
			 */
			title: string
		}
		traffic: {
			/**
			 * A​c​t​i​v​e​ ​c​o​n​n​e​c​t​i​o​n​s​,​ ​r​e​c​e​n​t​l​y​ ​c​l​o​s​e​d​ ​c​o​n​n​e​c​t​i​o​n​s​,​ ​a​n​d​ ​e​f​f​e​c​t​i​v​e​ ​r​u​l​e​s​ ​w​i​l​l​ ​s​h​a​r​e​ ​o​n​e​ ​i​n​v​e​s​t​i​g​a​t​i​o​n​ ​s​u​r​f​a​c​e​.
			 */
			description: string
			/**
			 * D​e​s​t​i​n​a​t​i​o​n​,​ ​p​r​o​c​e​s​s​,​ ​t​r​a​f​f​i​c​,​ ​r​u​l​e​,​ ​a​n​d​ ​r​o​u​t​e​ ​c​h​a​i​n​.
			 */
			itemOneDetail: string
			/**
			 * A​c​t​i​v​e
			 */
			itemOneLabel: string
			/**
			 * O​r​d​e​r​e​d​,​ ​s​e​a​r​c​h​a​b​l​e​ ​e​f​f​e​c​t​i​v​e​ ​r​u​l​e​ ​r​e​f​e​r​e​n​c​e​.
			 */
			itemThreeDetail: string
			/**
			 * R​u​l​e​s
			 */
			itemThreeLabel: string
			/**
			 * B​o​u​n​d​e​d​ ​l​o​c​a​l​ ​d​i​a​g​n​o​s​t​i​c​ ​h​i​s​t​o​r​y​.
			 */
			itemTwoDetail: string
			/**
			 * C​l​o​s​e​d
			 */
			itemTwoLabel: string
			/**
			 * N​o​ ​c​o​n​n​e​c​t​i​o​n​ ​s​t​r​e​a​m​ ​i​s​ ​a​t​t​a​c​h​e​d​;​ ​S​t​a​t​u​s​ ​v​a​l​u​e​s​ ​r​e​m​a​i​n​ ​f​i​x​t​u​r​e​ ​d​a​t​a​.
			 */
			prerequisite: string
			/**
			 * T​r​a​f​f​i​c
			 */
			title: string
		}
		events: {
			/**
			 * A​p​p​l​i​c​a​t​i​o​n​,​ ​c​o​r​e​,​ ​R​P​C​,​ ​a​n​d​ ​p​l​a​t​f​o​r​m​ ​e​v​e​n​t​s​ ​w​i​l​l​ ​s​u​p​p​o​r​t​ ​c​o​n​t​e​x​t​u​a​l​ ​r​e​c​o​v​e​r​y​ ​a​n​d​ ​g​u​i​d​e​d​ ​d​i​a​g​n​o​s​t​i​c​s​.
			 */
			description: string
			/**
			 * T​i​m​e​s​t​a​m​p​e​d​ ​s​o​u​r​c​e​ ​a​n​d​ ​s​e​v​e​r​i​t​y​ ​r​o​w​s​.
			 */
			itemOneDetail: string
			/**
			 * E​v​e​n​t​ ​s​t​r​e​a​m
			 */
			itemOneLabel: string
			/**
			 * E​x​p​l​i​c​i​t​ ​p​r​e​v​i​e​w​ ​a​n​d​ ​s​t​r​u​c​t​u​r​e​d​ ​r​e​d​a​c​t​i​o​n​.
			 */
			itemThreeDetail: string
			/**
			 * E​x​p​o​r​t
			 */
			itemThreeLabel: string
			/**
			 * L​a​y​e​r​e​d​ ​c​h​e​c​k​s​ ​w​i​t​h​ ​o​b​s​e​r​v​e​d​ ​s​c​o​p​e​.
			 */
			itemTwoDetail: string
			/**
			 * D​i​a​g​n​o​s​t​i​c​s
			 */
			itemTwoLabel: string
			/**
			 * N​o​ ​l​o​c​a​l​-​a​g​e​n​t​ ​e​v​e​n​t​ ​b​u​f​f​e​r​ ​o​r​ ​d​i​a​g​n​o​s​t​i​c​ ​r​u​n​n​e​r​ ​e​x​i​s​t​s​ ​y​e​t​.
			 */
			prerequisite: string
			/**
			 * E​v​e​n​t​s
			 */
			title: string
		}
		settings: {
			/**
			 * S​e​t​t​i​n​g​s​ ​w​i​l​l​ ​b​e​ ​o​r​g​a​n​i​z​e​d​ ​b​y​ ​o​u​t​c​o​m​e​ ​a​n​d​ ​w​i​l​l​ ​e​x​p​o​s​e​ ​o​n​l​y​ ​c​a​p​a​b​i​l​i​t​i​e​s​ ​c​o​n​f​i​r​m​e​d​ ​b​y​ ​t​h​e​ ​p​l​a​t​f​o​r​m​ ​a​d​a​p​t​e​r​.
			 */
			description: string
			/**
			 * S​y​s​t​e​m​ ​P​r​o​x​y​,​ ​f​u​t​u​r​e​ ​T​U​N​ ​s​e​t​u​p​,​ ​a​n​d​ ​s​t​a​r​t​u​p​.
			 */
			itemOneDetail: string
			/**
			 * C​a​p​t​u​r​e​ ​a​n​d​ ​s​t​a​r​t​u​p
			 */
			itemOneLabel: string
			/**
			 * T​h​e​m​e​,​ ​m​o​t​i​o​n​,​ ​u​p​d​a​t​e​,​ ​p​r​i​v​a​c​y​,​ ​a​n​d​ ​s​u​p​p​o​r​t​.
			 */
			itemThreeDetail: string
			/**
			 * A​p​p​l​i​c​a​t​i​o​n
			 */
			itemThreeLabel: string
			/**
			 * C​o​r​e​ ​p​o​l​i​c​y​ ​w​i​t​h​ ​c​l​e​a​r​ ​r​i​s​k​ ​b​o​u​n​d​a​r​i​e​s​.
			 */
			itemTwoDetail: string
			/**
			 * N​e​t​w​o​r​k​ ​a​n​d​ ​D​N​S
			 */
			itemTwoLabel: string
			/**
			 * P​l​a​t​f​o​r​m​ ​c​a​p​a​b​i​l​i​t​i​e​s​ ​a​r​e​ ​f​i​x​t​u​r​e​-​o​n​l​y​ ​i​n​ ​t​h​i​s​ ​p​r​o​d​u​c​t​i​o​n​ ​f​o​u​n​d​a​t​i​o​n​.
			 */
			prerequisite: string
			/**
			 * S​e​t​t​i​n​g​s
			 */
			title: string
		}
	}
	notFound: {
		/**
		 * T​h​i​s​ ​r​o​u​t​e​ ​i​s​ ​n​o​t​ ​o​n​e​ ​o​f​ ​t​h​e​ ​s​i​x​ ​s​t​a​b​l​e​ ​p​r​o​d​u​c​t​ ​d​e​s​t​i​n​a​t​i​o​n​s​.
		 */
		description: string
		/**
		 * R​e​t​u​r​n​ ​t​o​ ​S​t​a​t​u​s
		 */
		returnToStatus: string
		/**
		 * P​a​g​e​ ​n​o​t​ ​f​o​u​n​d
		 */
		title: string
	}
	errors: {
		/**
		 * T​h​e​ ​c​o​m​m​a​n​d​ ​f​a​i​l​e​d​.
		 */
		command: string
		/**
		 * U​n​a​b​l​e​ ​t​o​ ​l​o​a​d​ ​S​t​a​t​u​s​ ​d​a​t​a​.
		 */
		loadStatus: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Pending
		 */
		pending: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Unavailable
		 */
		unavailable: () => LocalizedString
	}
	language: {
		/**
		 * Change language. Current language: {language}
		 */
		current: (arg: { language: string }) => LocalizedString
		/**
		 * English
		 */
		english: () => LocalizedString
		/**
		 * Language
		 */
		label: () => LocalizedString
		/**
		 * 简体中文
		 */
		simplifiedChinese: () => LocalizedString
	}
	navigation: {
		/**
		 * Events
		 */
		events: () => LocalizedString
		/**
		 * Primary navigation
		 */
		primary: () => LocalizedString
		/**
		 * Profiles
		 */
		profiles: () => LocalizedString
		/**
		 * Routes
		 */
		routes: () => LocalizedString
		/**
		 * Workspace sections
		 */
		sections: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Traffic
		 */
		traffic: () => LocalizedString
	}
	toolbar: {
		/**
		 * The current screen uses simulated data. No action changes system or network state.
		 */
		demoDescription: () => LocalizedString
		/**
		 * Demo mode
		 */
		demoMode: () => LocalizedString
		/**
		 * This action changes local fixture data only and does not change system or network state.
		 */
		fixtureActionDescription: () => LocalizedString
		/**
		 * Loading fixture…
		 */
		loadingFixture: () => LocalizedString
		/**
		 * Profiles
		 */
		profiles: () => LocalizedString
		/**
		 * Switch profile. Current profile: {profile}
		 */
		switchProfile: (arg: { profile: string }) => LocalizedString
	}
	proxyControl: {
		/**
		 * Disable the proxy demo state
		 */
		disableAria: () => LocalizedString
		/**
		 * Disable proxy
		 */
		disable: () => LocalizedString
		/**
		 * Enable the proxy demo state
		 */
		enableAria: () => LocalizedString
		/**
		 * Enable proxy
		 */
		enable: () => LocalizedString
		/**
		 * Proxy running
		 */
		running: () => LocalizedString
	}
	status: {
		/**
		 * Active rules
		 */
		activeRules: () => LocalizedString
		/**
		 * Connections
		 */
		connections: () => LocalizedString
		/**
		 * Current session
		 */
		currentSessionAria: () => LocalizedString
		/**
		 * Downloaded
		 */
		downloaded: () => LocalizedString
		/**
		 * Fixture activity at a glance.
		 */
		fixtureActivity: () => LocalizedString
		/**
		 * Fixture data is unavailable.
		 */
		fixtureUnavailable: () => LocalizedString
		/**
		 * Groups
		 */
		groups: () => LocalizedString
		/**
		 * Frequently used policy groups
		 */
		groupsAria: () => LocalizedString
		/**
		 * Loading typed fixture data…
		 */
		loading: () => LocalizedString
		/**
		 * Memory
		 */
		memory: () => LocalizedString
		/**
		 * Direct
		 */
		modeDirect: () => LocalizedString
		/**
		 * Global
		 */
		modeGlobal: () => LocalizedString
		/**
		 * Rule
		 */
		modeRule: () => LocalizedString
		/**
		 * No selection
		 */
		noSelection: () => LocalizedString
		/**
		 * Open live traffic
		 */
		openLiveTraffic: () => LocalizedString
		/**
		 * Routing mode
		 */
		routingMode: () => LocalizedString
		/**
		 * Reconnecting to the local agent. Last confirmed data is stale.
		 */
		reconnecting: () => LocalizedString
		/**
		 * Session
		 */
		session: () => LocalizedString
		/**
		 * Services
		 */
		services: () => LocalizedString
		/**
		 * The local agent is disconnected. Last confirmed data is stale.
		 */
		staleData: () => LocalizedString
		/**
		 * Traffic capture
		 */
		trafficCapture: () => LocalizedString
		/**
		 * Uploaded
		 */
		uploaded: () => LocalizedString
		/**
		 * Uptime
		 */
		uptime: () => LocalizedString
		/**
		 * Most used first.
		 */
		usedFirst: () => LocalizedString
		/**
		 * View all
		 */
		viewAll: () => LocalizedString
		/**
		 * {count} available children
		 */
		availableChildren: (arg: { count: number }) => LocalizedString
	}
	capture: {
		/**
		 * Got it
		 */
		acknowledge: () => LocalizedString
		/**
		 * This changes fixture state only and does not modify the system network configuration.
		 */
		description: () => LocalizedString
		/**
		 * Learn the difference between System Proxy and Enhanced Mode
		 */
		helpAria: () => LocalizedString
		/**
		 * System Proxy
		 */
		systemProxy: () => LocalizedString
		/**
		 * For applications that follow system proxy settings. Part 2 will provide the real capability through the platform adapter.
		 */
		systemProxyDescription: () => LocalizedString
		/**
		 * System Proxy and Enhanced Mode
		 */
		title: () => LocalizedString
		/**
		 * Enhanced Mode (TUN)
		 */
		tun: () => LocalizedString
		/**
		 * A future controlled native capability will capture broader traffic. Part 1 installs no permission and performs no network operation.
		 */
		tunDescription: () => LocalizedString
	}
	proxyPicker: {
		/**
		 * Select a child for this policy group. The selection is not global.
		 */
		description: () => LocalizedString
		/**
		 * No matching nodes.
		 */
		empty: () => LocalizedString
		/**
		 * Search available nodes
		 */
		searchAria: () => LocalizedString
		/**
		 * Search nodes
		 */
		searchPlaceholder: () => LocalizedString
	}
	services: {
		/**
		 * Add service
		 */
		add: () => LocalizedString
		/**
		 * Add a local demo monitor. No request will be sent.
		 */
		addDescription: () => LocalizedString
		/**
		 * Demo service added
		 */
		addedToast: () => LocalizedString
		/**
		 * Default demo services restored
		 */
		defaultRestoredToast: () => LocalizedString
		/**
		 * This removes only the local fixture monitor.
		 */
		deleteDescription: () => LocalizedString
		/**
		 * Delete {service}?
		 */
		deleteTitle: (arg: { service: string }) => LocalizedString
		/**
		 * Edit service
		 */
		edit: () => LocalizedString
		/**
		 * Edit fixture monitor:
		 */
		editAria: () => LocalizedString
		/**
		 * No fixture service monitors
		 */
		empty: () => LocalizedString
		/**
		 * Fixture endpoint latency.
		 */
		endpointDescription: () => LocalizedString
		/**
		 * Enter a title.
		 */
		labelError: () => LocalizedString
		/**
		 * Manage
		 */
		manage: () => LocalizedString
		/**
		 * Fixture metadata only. Part 1 never requests this endpoint.
		 */
		metadataDescription: () => LocalizedString
		/**
		 * Probe URL
		 */
		probeUrl: () => LocalizedString
		/**
		 * Demo service removed
		 */
		removedToast: () => LocalizedString
		/**
		 * Restore defaults
		 */
		restoreDefaults: () => LocalizedString
		/**
		 * Service name
		 */
		serviceName: () => LocalizedString
		/**
		 * Title
		 */
		title: () => LocalizedString
		/**
		 * Demo service updated
		 */
		updatedToast: () => LocalizedString
		/**
		 * Only HTTP and HTTPS metadata is accepted by the fixture adapter.
		 */
		urlDescription: () => LocalizedString
		/**
		 * Enter a valid HTTP or HTTPS URL.
		 */
		urlError: () => LocalizedString
		/**
		 * Service latency monitors
		 */
		aria: () => LocalizedString
		/**
		 * this service
		 */
		fallbackName: () => LocalizedString
	}
	destination: {
		/**
		 * Current state
		 */
		currentState: () => LocalizedString
		/**
		 * Production foundation
		 */
		foundation: () => LocalizedString
		/**
		 * Part 2+
		 */
		partTwo: () => LocalizedString
		/**
		 * Stable page ownership, without simulated functionality.
		 */
		plannedDescription: () => LocalizedString
		/**
		 * Planned structure
		 */
		plannedStructure: () => LocalizedString
		routes: {
			/**
			 * The complete policy-group hierarchy will live here without flattening groups into a global node list.
			 */
			description: () => LocalizedString
			/**
			 * Preserve nested selectors and strategy groups.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Group tree
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Run cancellable group- and child-scoped checks.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Latency
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Match complete opaque Unicode labels.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Search
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * Waiting for typed policy-group DTOs from the Part 2 local agent.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Routes
			 */
			title: () => LocalizedString
		}
		profiles: {
			/**
			 * Profile sources, validation, activation, and last-known-good state will remain separate from runtime routes.
			 */
			description: () => LocalizedString
			/**
			 * Local file and HTTPS URL sources.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Import
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Reversible activation with explicit outcomes.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Activate
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Compatibility and conflict preflight.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Validate
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * No production profile store exists in Part 1.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Profiles
			 */
			title: () => LocalizedString
		}
		traffic: {
			/**
			 * Active connections, recently closed connections, and effective rules will share one investigation surface.
			 */
			description: () => LocalizedString
			/**
			 * Destination, process, traffic, rule, and route chain.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Active
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Ordered, searchable effective rule reference.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Rules
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Bounded local diagnostic history.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Closed
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * No connection stream is attached; Status values remain fixture data.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Traffic
			 */
			title: () => LocalizedString
		}
		events: {
			/**
			 * Application, core, RPC, and platform events will support contextual recovery and guided diagnostics.
			 */
			description: () => LocalizedString
			/**
			 * Timestamped source and severity rows.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Event stream
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Explicit preview and structured redaction.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Export
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Layered checks with observed scope.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Diagnostics
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * No local-agent event buffer or diagnostic runner exists yet.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Events
			 */
			title: () => LocalizedString
		}
		settings: {
			/**
			 * Settings will be organized by outcome and will expose only capabilities confirmed by the platform adapter.
			 */
			description: () => LocalizedString
			/**
			 * System Proxy, future TUN setup, and startup.
			 */
			itemOneDetail: () => LocalizedString
			/**
			 * Capture and startup
			 */
			itemOneLabel: () => LocalizedString
			/**
			 * Theme, motion, update, privacy, and support.
			 */
			itemThreeDetail: () => LocalizedString
			/**
			 * Application
			 */
			itemThreeLabel: () => LocalizedString
			/**
			 * Core policy with clear risk boundaries.
			 */
			itemTwoDetail: () => LocalizedString
			/**
			 * Network and DNS
			 */
			itemTwoLabel: () => LocalizedString
			/**
			 * Platform capabilities are fixture-only in this production foundation.
			 */
			prerequisite: () => LocalizedString
			/**
			 * Settings
			 */
			title: () => LocalizedString
		}
	}
	notFound: {
		/**
		 * This route is not one of the six stable product destinations.
		 */
		description: () => LocalizedString
		/**
		 * Return to Status
		 */
		returnToStatus: () => LocalizedString
		/**
		 * Page not found
		 */
		title: () => LocalizedString
	}
	errors: {
		/**
		 * The command failed.
		 */
		command: () => LocalizedString
		/**
		 * Unable to load Status data.
		 */
		loadStatus: () => LocalizedString
	}
}

export type Formatters = {}
