// Generated by scripts/generate-presentation-contract.ts; do not edit.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Locale {
    En,
    ZhCn,
}
impl Locale {
    pub const ALL: [Self; 2] = [Self::En, Self::ZhCn];
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::En => "en",
            Self::ZhCn => "zh-CN",
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NativeMessageId {
    StatusOpenMish,
    StatusOpenBrowser,
    StatusOpenRoutes,
    StatusOpenProfiles,
    StatusOpenTraffic,
    StatusOpenEvents,
    StatusOpenSettings,
    StatusLaunchProxy,
    StatusLaunchProxyPending,
    StatusLaunchProxyFailed,
    StatusStopProxy,
    StatusAutoStartProxy,
    StatusQuit,
    StatusLiveIdle,
    StatusLiveUnavailable,
    StatusLiveMostActiveNode,
    StatusLiveRate,
    ApplicationSettings,
    ApplicationFind,
    ApplicationQuit,
}
impl NativeMessageId {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::StatusOpenMish => "status.open-mish",
            Self::StatusOpenBrowser => "status.open-browser",
            Self::StatusOpenRoutes => "status.open-routes",
            Self::StatusOpenProfiles => "status.open-profiles",
            Self::StatusOpenTraffic => "status.open-traffic",
            Self::StatusOpenEvents => "status.open-events",
            Self::StatusOpenSettings => "status.open-settings",
            Self::StatusLaunchProxy => "status.launch-proxy",
            Self::StatusLaunchProxyPending => "status.launch-proxy-pending",
            Self::StatusLaunchProxyFailed => "status.launch-proxy-failed",
            Self::StatusStopProxy => "status.stop-proxy",
            Self::StatusAutoStartProxy => "status.auto-start-proxy",
            Self::StatusQuit => "status.quit",
            Self::StatusLiveIdle => "status.live.idle",
            Self::StatusLiveUnavailable => "status.live.unavailable",
            Self::StatusLiveMostActiveNode => "status.live.most-active-node",
            Self::StatusLiveRate => "status.live.rate",
            Self::ApplicationSettings => "application.settings",
            Self::ApplicationFind => "application.find",
            Self::ApplicationQuit => "application.quit",
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NativeMessage<'a> {
    StatusOpenMish,
    StatusOpenBrowser,
    StatusOpenRoutes,
    StatusOpenProfiles,
    StatusOpenTraffic,
    StatusOpenEvents,
    StatusOpenSettings,
    StatusLaunchProxy,
    StatusLaunchProxyPending,
    StatusLaunchProxyFailed,
    StatusStopProxy,
    StatusAutoStartProxy,
    StatusQuit,
    StatusLiveIdle,
    StatusLiveUnavailable,
    StatusLiveMostActiveNode {
        label: &'a str,
    },
    StatusLiveRate {
        direction: &'a str,
        rate: &'a str,
        total: &'a str,
    },
    ApplicationSettings,
    ApplicationFind,
    ApplicationQuit,
}
impl NativeMessage<'_> {
    pub const fn id(self) -> NativeMessageId {
        match self {
            Self::StatusOpenMish => NativeMessageId::StatusOpenMish,
            Self::StatusOpenBrowser => NativeMessageId::StatusOpenBrowser,
            Self::StatusOpenRoutes => NativeMessageId::StatusOpenRoutes,
            Self::StatusOpenProfiles => NativeMessageId::StatusOpenProfiles,
            Self::StatusOpenTraffic => NativeMessageId::StatusOpenTraffic,
            Self::StatusOpenEvents => NativeMessageId::StatusOpenEvents,
            Self::StatusOpenSettings => NativeMessageId::StatusOpenSettings,
            Self::StatusLaunchProxy => NativeMessageId::StatusLaunchProxy,
            Self::StatusLaunchProxyPending => NativeMessageId::StatusLaunchProxyPending,
            Self::StatusLaunchProxyFailed => NativeMessageId::StatusLaunchProxyFailed,
            Self::StatusStopProxy => NativeMessageId::StatusStopProxy,
            Self::StatusAutoStartProxy => NativeMessageId::StatusAutoStartProxy,
            Self::StatusQuit => NativeMessageId::StatusQuit,
            Self::StatusLiveIdle => NativeMessageId::StatusLiveIdle,
            Self::StatusLiveUnavailable => NativeMessageId::StatusLiveUnavailable,
            Self::StatusLiveMostActiveNode { .. } => NativeMessageId::StatusLiveMostActiveNode,
            Self::StatusLiveRate { .. } => NativeMessageId::StatusLiveRate,
            Self::ApplicationSettings => NativeMessageId::ApplicationSettings,
            Self::ApplicationFind => NativeMessageId::ApplicationFind,
            Self::ApplicationQuit => NativeMessageId::ApplicationQuit,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NativeActionId {
    ApplicationFind,
    ApplicationQuit,
    ApplicationSettings,
    StatusBarOpenBrowser,
    StatusBarOpenEvents,
    StatusBarOpenMish,
    StatusBarOpenProfiles,
    StatusBarOpenRoutes,
    StatusBarOpenSettings,
    StatusBarOpenTraffic,
    StatusBarQuit,
    StatusBarToggleLaunchOnStart,
    StatusBarToggleProxy,
}
impl NativeActionId {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ApplicationFind => "application.find",
            Self::ApplicationQuit => "application.quit",
            Self::ApplicationSettings => "application.settings",
            Self::StatusBarOpenBrowser => "status-bar.open-browser",
            Self::StatusBarOpenEvents => "status-bar.open-events",
            Self::StatusBarOpenMish => "status-bar.open-mish",
            Self::StatusBarOpenProfiles => "status-bar.open-profiles",
            Self::StatusBarOpenRoutes => "status-bar.open-routes",
            Self::StatusBarOpenSettings => "status-bar.open-settings",
            Self::StatusBarOpenTraffic => "status-bar.open-traffic",
            Self::StatusBarQuit => "status-bar.quit",
            Self::StatusBarToggleLaunchOnStart => "status-bar.toggle-launch-on-start",
            Self::StatusBarToggleProxy => "status-bar.toggle-proxy",
        }
    }
}
