[package]
name = "mish-state-machine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { version = "1.53.0", features = ["macros", "rt", "sync", "time"] }
tokio-util = "0.7.18"

[dev-dependencies]
tokio = { version = "1.53.0", features = ["macros", "rt-multi-thread", "test-util"] }
